src/lib/containers/StackedRowHomebrew.js
=> reset query wrapper on new props update case

src/lib/containers/row_renderers/Study.tsx, src/lib/containers/row_renderers/utils/ShowMore.tsx, src/lib/style/katex.scss
Fixed study card links to use id field of table data
Fixed Show More button to have the right styling
=> PORTALS-180 PORTALS-165

src/__tests__/lib/containers/MarkdownSynapse.test.tsx, src/demo/containers/Demo.tsx, src/lib/containers/MarkdownSynapse.tsx, src/lib/containers/widgets/SynapseImage.tsx, src/lib/containers/widgets/SynapsePlot.tsx, src/lib/style/Portal.css, src/lib/style/Portal.scss
Added tests to MarkdownSynapse, improved readability
Added css to markdown code blocks
=> PORTALS-369

package.json, src/demo/containers/playground/UserCardDemo.tsx, src/lib/style/Portal.css, src/lib/style/Portal.scss
extra padding-left does not apply to small card
=> fix spacing for profiles with lots of info. 

src/lib/containers/row_renderers/Dataset.tsx, src/lib/containers/row_renderers/utils/Icon.tsx, src/lib/style/Cards.scss
fixed dataset icon to actually use the dataset icon
fixed button font size
fixed spacing...
=> PORTALS-445

src/lib/containers/UserCardMedium.tsx, src/lib/containers/UserCardSmall.tsx, src/lib/containers/row_renderers/utils/Icon.tsx, src/lib/style/Cards.scss, src/lib/style/Portal.css, src/lib/style/Portal.scss
fixes underline in user cards and icon on dataset cards
=> PORTALS-451, SWC-4792

README.md, src/demo/containers/playground/UserCardDemo.tsx, src/lib/containers/UserCard.tsx, src/lib/containers/UserCardMedium.tsx, src/lib/containers/UserCardSmall.tsx
removed unused prop profileClickHandler
=> added prop for custom link in user cards

src/__tests__/lib/containers/drug_upload_tool/Header.test.tsx, src/__tests__/lib/containers/drug_upload_tool/NavButtons.test.tsx, src/__tests__/lib/containers/drug_upload_tool/StepsSideNav.test.tsx, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/Header.tsx, src/lib/containers/drug_upload_tool/NavButtons.tsx, src/lib/containers/drug_upload_tool/StepsSideNav.scss, src/lib/containers/drug_upload_tool/StepsSideNav.tsx, src/lib/containers/drug_upload_tool/_Vars.scss, src/lib/containers/drug_upload_tool/types.ts
=> feat(CNT): NavButtons, Header, and StepsSideNav components

package.json, src/demo/containers/App.tsx, src/lib/containers/drug_upload_tool/DrugUploadForm.tsx, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/StepsSideNav.scss, src/lib/containers/drug_upload_tool/StepsSideNav.tsx, src/lib/containers/drug_upload_tool/SummaryTable.tsx, src/lib/containers/drug_upload_tool/UserFileGrid.tsx, yarn.lock
This has several enhancements and updates. 
1. Added a toggle to only show help when it's toggled
2. Cleaned up the file gird and added another parameter to have the 'add new ...' button text configurable through property
3. fixed the formatting on the summary page
4. added some logic for the hidden 'included' field to accommodate for 'required' properties on conditional screens
=> Portals 560

package.json, src/demo/containers/App.tsx, src/demo/containers/playground/FormServicesIntegrationDemo.tsx
bump package version + create new FormGroup and update Id for Drug Upload Tool
=> chore(CNT): bump package version + add/change FormGroupId

package.json, src/lib/containers/drug_upload_tool/DrugUploadForm.tsx, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/DrugUploadTool.tsx, src/lib/containers/drug_upload_tool/StepsSideNav.scss, src/lib/containers/drug_upload_tool/UserFileGrid.tsx, src/lib/containers/drug_upload_tool/_Vars.scss
Added ability to theme the drug tool by taking an approach from[ this article](https://medium.com/@dmitriy.borodiy/easy-color-theming-with-scss-bc38fd5734d1)
=> style(CNT): ability to theme the tool

src/lib/containers/drug_upload_tool/DrugUploadForm.tsx, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/DrugUploadTool.tsx, src/lib/containers/drug_upload_tool/SummaryTable.tsx
mostly style changes. Corresponding JIRAs attached
=> Drug Upload Tool - style fixes

src/__tests__/lib/containers/drug_upload_tool/DrugUploadForm.test.tsx
=> test(DrugTool): add await and and fix the spies

package.json, src/__tests__/lib/containers/drug_upload_tool/SummaryTable.test.tsx, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/SummaryTable.tsx, src/lib/containers/drug_upload_tool/UserFileGrid.tsx, src/lib/containers/drug_upload_tool/print.scss, src/mocks/contribReqFormSchema.json, src/mocks/contribReqFormUiSchema.json
1.  ability to print summary data [PORTALS-622](https://sagebionetworks.jira.com/projects/PORTALS/issues/PORTALS-622?filter=allopenissues&orderby=priority%20DESC)
View on the screen:
Resulting PDF after print to pdf
[Synapse React Client.pdf](https://github.com/Sage-Bionetworks/Synapse-React-Client/files/3805969/Synapse.React.Client.pdf)
2. added changes to the contribution request form data to version control (no functional change)
=> Ability to print summary data

package.json, src/lib/containers/drug_upload_tool/DrugUploadTool.scss, src/lib/containers/drug_upload_tool/UserFileGrid.tsx, src/mocks/drugToolFormNavSchema.json
- minor style and layout updates for remaining jiras
- fixed the 'key' warning for the user grid
=> Drug Upload Tool updates

package.json, src/demo/SingleFileBuild/index.html, src/lib/rollup.index.ts, src/umd/synapse-react-client.production.min.js
and bump version (to prepare for merge into master)
=> SWC-5052: export HasAccess component (test in umd build page)

src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/FacetFilter.tsx, src/lib/style/Core.scss
[https://sagebionetworks.jira.com/browse/PORTALS-883](https://sagebionetworks.jira.com/browse/PORTALS-883)
borders and sort/filter alignment
few columns:
many columns:
=> fix(SRC style): Table column header formatting

src/lib/containers/QueryWrapper.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/style/Core.scss
https://sagebionetworks.jira.com/browse/PORTALS-884
before:
after:
=> fix(SRC style): PORTALS-884 Proper spacing above the table

src/__tests__/lib/containers/SynapseTable.test.tsx, src/demo/containers/Demo.tsx, src/lib/containers/table/SynapseTable.tsx
https://sagebionetworks.jira.com/browse/PORTALS-959
=> fix(SRC): fix for date formatting in SynapseTable

src/__tests__/lib/containers/widgets/Checkbox.test.tsx, src/__tests__/lib/containers/widgets/RadioGroup.test.tsx, src/__tests__/lib/containers/widgets/Range.test.tsx, src/demo/containers/playground/Playground.tsx, src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/containers/widgets/Range.tsx
This PR adds Checkbox, RadioGroup and Range (for numbers and dates) controls into the /widgets
=> Checkbox, RadioGroup, and Range Controls

package.json, src/__tests__/lib/containers/widgets/RangeSlider.test.tsx, src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/widgets/RangeSlider.scss, src/lib/containers/widgets/RangeSlider.tsx, yarn.lock
More info about the lib can be found here: https://www.npmjs.com/package/react-compound-slider/v/0.17.0
=> feat(rangeSlider): add rangeSliderWidget

package.json, src/__tests__/lib/containers/widgets/ImageButtonWithTooltip.test.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx, src/lib/containers/table/table-top/ExpandTable.tsx, src/lib/containers/widgets/ImageButtonWithTooltip.tsx, yarn.lock
https://sagebionetworks.jira.com/browse/PORTALS-975
- created the new control
- replaced the current icon/tooltip, image/tooltip, dropdown-toggle/tooltip in the table
- installed and using `testing-library/react` for testing
=> feat( PORTALS-975): Image button with tooltip control for top nav in tables

src/lib/containers/table/SynapseTable.tsx, src/lib/style/Core.scss
=> fix(SCSS): fix to table formatting

src/lib/containers/QueryWrapperMenu.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx
=> fix(chore): fix key warnings for query wrapper and EnumFacetFilter

src/demo/containers/Demo.tsx, src/lib/assets/icons/file-dotted.svg, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/Range.tsx, src/lib/containers/widgets/RangeSlider.scss, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx, src/lib/style/Core.scss, src/lib/style/Vars.scss
https://sagebionetworks.jira.com/browse/PORTALS-800
Also have fixed a bug with the facet filter and adjusted some styles
No records returned as a result of user filtering:
No records returned
=> fix(PORTALS-800): hide table if there are 0 rows

CONTRIBUTING.md
changes from https://github.com/Sage-Bionetworks/Synapse-React-Client/pull/354 (closed) + css conventions
=> docs(PORTALS-652): update docs for css refactor

src/__tests__/lib/containers/widgets/ElementWithTooltip.test.tsx, src/__tests__/lib/containers/widgets/ImageButtonWithTooltip.test.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx, src/lib/containers/table/table-top/ExpandTable.tsx, src/lib/containers/widgets/ElementWithTooltip.tsx, src/lib/containers/widgets/ImageButtonWithTooltip.tsx
If the column value length > 20 chars trim it and show the full value on hover
=> (PORTALS-746): long value handling in tables

src/lib/containers/RssFeed.tsx
and fix potential memory leak in rss feed (do not set state if component is no longer mounted)
=> Remove Node.js require statement

src/lib/containers/QueryWrapperMenu.tsx, src/lib/containers/table/SynapseTable.tsx, yarn.lock
- removed align center on HasAccess table column to fix (PORTALS-984)
- put next/previous buttons in div and text-align right instead of pull-right, removed margin, fixes PORTALS-985
- Formatting from linter on synapse table
=> PORTALS-984

package.json, src/demo/containers/playground/Playground.tsx, src/lib/containers/download_list/DownloadListTable.tsx
SWC can use push instead of polling
=> add ability to specify a DownloadList changed event handler

src/__tests__/lib/utils/functions/sqlFunctions.test.ts, src/lib/containers/widgets/SynapsePlot.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/functions/sqlFunctions.ts
1. Fix getFullQueryTableResults
2. Utility function to get synapse entityId from sql string
=> Synapse related enhancements

src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/widgets/themes-plot/BarPlot.tsx, src/lib/containers/widgets/themes-plot/DotPlot.tsx, src/lib/containers/widgets/themes-plot/ThemesPlot.tsx, src/lib/containers/widgets/themes-plot/types.ts
Just some cleanup, adding the legend and surfacing the color/style props
=> fix(PORTALS-1043): PR feedback and make colors configurable

src/lib/utils/SynapseClient.ts
do not ask for the session token
=> getOAuth2RequestDescription is not an authenticated call

src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/widgets/ElementWithTooltip.tsx, src/lib/containers/widgets/themes-plot/BarPlot.tsx, src/lib/containers/widgets/themes-plot/DotPlot.tsx, src/lib/containers/widgets/themes-plot/ThemesPlot.tsx, src/lib/containers/widgets/themes-plot/types.ts, src/lib/style/components/_all.scss, src/lib/style/components/_themes-plot.scss
UI changes to acommodate design feedback
=> fix(PORTALS-1086): research themes UI scrub

src/lib/containers/widgets/themes-plot/ThemesPlot.tsx, src/lib/style/components/_themes-plot.scss
=> fix(PORTALS-1086): add 'research themes' label on the left

src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/widgets/themes-plot/ThemesPlot.tsx
=> fix(PORTALS-1086): adjust colors on the bar graphs and reverse legend

src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/FacetFilterHeader.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_query-filter.scss, src/lib/style/components/_themes-plot.scss
https://sagebionetworks.jira.com/browse/PORTALS-1099 - Facet text should wrap correctly
https://sagebionetworks.jira.com/browse/PORTALS-1104 - Facet numbers should be right aligned
https://sagebionetworks.jira.com/browse/PORTALS-1105 - Facet show all should show total number of facets
https://sagebionetworks.jira.com/browse/PORTALS-1106
=> EnumFacetFilter UI changes

src/demo/containers/playground/NewsFeedDemo.tsx, src/demo/containers/playground/Playground.tsx, src/demo/containers/playground/SingleNewsFeedPostDemo.tsx, src/lib/containers/NewsFeedMenu.tsx, src/lib/containers/RssFeed.tsx, src/lib/containers/SingleNewsFeedPost.tsx
Adds a SingleNewsFeedPost component - all url query params are passed through to the rss feed url.
=> PORTALS-1072

src/lib/containers/GenericCard.tsx, src/lib/style/components/_cards.scss
capitalize labels in header card
=> fix spacing around comma, remove unused css class

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/style/components/facet_nav/_facet-nav-panel.scss
=> PORTALS-1262

src/lib/containers/TotalQueryResults.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/row_renderers/utils/CardFooter.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/table/table-top/ExpandTable.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/style/base/_core.scss, src/lib/style/components/_total-query-results.scss
PORTALS-1294
PORTALS-1300
PORTALS-1306
cleanup from last PR
=> Explore 2.0 scrub

src/lib/containers/SearchV2.tsx
The css class is needed for fixing https://sagebionetworks.jira.com/browse/PORTALS-1332
=> Add back css class deleted by accident

src/lib/containers/MarkdownSynapse.tsx, src/lib/containers/access_requirement_list/AcceptedRequirements.tsx, src/lib/style/components/_access-requirement-list.scss
PORTALS-1448: if managed ACT AR and user is approved, show link to AR page where they can update their request (should something change).
=> PORTALS-1450: style returned from md processing is unexpected type (string)

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/style/components/_total-query-results.scss, src/lib/style/components/facet_nav/_facet-nav-panel.scss
=> PORTALS-1233

src/lib/containers/TotalQueryResults.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx
alias special synapse value with 'unannotated'
=> PORTALS-1347

src/lib/containers/widgets/facet-nav/FacetNav.tsx
- graph filter is broken on staging
- this logic should get refactored in the future but the quickest fix is to revert back
=> revert change to fix graph filter not working

src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/facet-nav/FacetNavPanel.test.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx
🤞 
https://sagebionetworks.jira.com/browse/PORTALS-1493
this pr fixes broken facet filtering from the dropdown
also a small ux tweak which is that the user should not be able to turn the all checkbox off since
that is a no-op
=> fix filters in graphs

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx
Changed Export Metadata -> Export Table
Also fixed broken queries by passing in lastQueryRequest to facetnavpanel, o.w. it would reset each time
=> PORTALS-1498/1493

README.md, package.json
=> Portals 1508

src/lib/containers/Search.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx
Theres a few places where the offset needs to be reset. It would also be good to refactor these methods to a single one in the future.
=> reset offset

src/demo/containers/playground/MarkdownSynapseDemo.tsx, src/lib/containers/Error.tsx, src/lib/containers/MarkdownSynapse.tsx, src/lib/utils/SynapseClient.ts
added error component to markdownsynapse
=> Follow up on PORTALS-1526

src/demo/containers/playground/Playground.tsx, src/demo/containers/playground/UpsetPlotDemo.tsx, src/lib/containers/UpsetPlot.tsx
(note that this particular error only shows up on staging psychencode if you are logged in as a user who has access to all files in the project.
=> PORTALS-1522: improve error handling, and check for null annotation value

package.json, src/demo/containers/playground/GoalsDemo.tsx, src/demo/containers/playground/Playground.tsx, src/lib/containers/Error.tsx, src/lib/containers/Goals.tsx, src/lib/containers/QueryCount.tsx, src/lib/containers/UpsetPlot.tsx, src/lib/index.ts, src/lib/style/components/_all.scss, src/lib/style/components/_goals.scss, yarn.lock
- bump react-scripts to fix dependabot alerts
- extended the Error component to detect the error coming in, put in the UpSet plot
- Added goals component
preview -
zoomed in preview -
=> PORTALS-1552

src/demo/containers/playground/Playground.tsx, src/lib/containers/Goals.tsx, src/lib/containers/Resources.tsx, src/lib/index.ts, src/lib/style/components/_all.scss, src/lib/style/components/_resources.scss
Lockdown column names, move validation to synapse
Added resources component
Preview of component
=> lockdown column names, remove validation, added resources component

src/lib/containers/SearchV2.tsx
if specified, the `searchable` prop will now specify the _order_ of the columns in the dropdown. Otherwise, if not specified, the ordering of the data column models will be used.
=> order by searchable prop and remove hint text

src/demo/containers/playground/PeopleProfileDemo.tsx, src/lib/containers/UserCardListRotate.tsx, src/lib/style/base/_core.scss, src/lib/style/components/_cards-rotate.scss
1. Change content scrolling to auto
2. Add background color for component div
3. Add loading bar
4. Add explore all user link
=> PORTALS-1557: Multiple css and markup updates

src/demo/containers/playground/PeopleProfileDemo.tsx, src/demo/style/DemoStyle.scss, src/lib/containers/UserCardListRotate.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/base/_core.scss, src/lib/template_style/_theme.scss
1. Move button css to core
2. Move homepage color background color to theme file
=> PORTALS-1557: Move css code to core and theme files

src/lib/style/base/_core.scss
1. Fix scrollbar not visible for some users when set to css scroll: auto
2. Ensure card color is still white when component background has color.
=> Portals-1557: Fix scrollbar and card background

src/__tests__/lib/containers/FacetsPlotNav.test.tsx, src/__tests__/lib/containers/StackedBarChart.test.tsx, src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/RangeFacetFilter.test.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx, src/lib/utils/SynapseConstants.ts
change "Not Set" ->  unannotated
=> PORTALS-1595

src/lib/containers/row_renderers/Dataset.tsx
=> fix rendering of multi-value content in dataset card

src/demo/containers/playground/UpsetPlotDemo.tsx, src/lib/containers/UpsetPlot.tsx
…esponse sent in async job response
=> PORTALS-1619:  improve error handling

src/__tests__/lib/utils/functions/urlConfiguration.test.ts, src/lib/utils/functions/sqlFunctions.ts
=> PORTALS-1621

package.json, src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/style/base/_core.scss, src/lib/style/components/facet_nav/_facet-nav.scss
1. update SRC demo site container class to match the portal side. 
2. add a class to remove restriction on 1440 max width
3. use flex layout for plots when the page uses full width
=> PORTALS-1339: unset page max width

src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/RangeFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/query-filter/QueryFilter.test.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx
https://sagebionetworks.jira.com/browse/PORTALS-1352
=> PORTALS-1352: Collapse all but the first 3 facets in QueryFilter

package.json, yarn.lock
auto-update for patch and minor releases.  checking in results after rebuild
=> update to node-sass 4.13.1

package.json, src/__tests__/lib/containers/PageProgress.test.tsx, src/lib/containers/PageProgress.md, src/lib/containers/PageProgress.tsx, src/lib/index.ts, src/lib/rollup.index.ts, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_all.scss, src/lib/style/components/_page-progress.scss, src/lib/style/components/_terms-and-conditions.scss
=> Portals-1765: Page progress component

package.json, src/lib/style/components/_terms-and-conditions.scss
=> PORTALS-1769: Fix firefox checkmark alignment bug

package.json, src/lib/containers/TermsAndConditions.tsx, src/lib/containers/TermsAndConditionsItem.tsx, src/lib/style/components/_terms-and-conditions.scss
Added additional terms and conditions text
=> Portals-1761: Add terms copy

.github/workflows/npmpublish.yml, package.json, src/lib/containers/evaluation_queues/EvaluationCard.tsx, src/lib/style/components/evaluation_queue/_evaluation-card.scss
Has changes from SWC-5199 as well.
Note that the initial build from Sage-Bionetworks/Synapse-React-Client will fail, since it will not have the NPM secret access token...
=> Released 1.15.52 of SRC using a new GitHub Actions workflow script

src/lib/style/components/_synapse-homepage.scss
https://sagebionetworks.jira.com/browse/SWC-5345
=> SWC-5345: Center text under API icons

package.json, src/lib/containers/evaluation_queues/EvaluationEditor.tsx, src/lib/utils/index.tsx, src/lib/utils/synapseTypes/Evaluation/Evaluation.ts, src/lib/utils/synapseTypes/Evaluation/EvaluationStatus.ts, src/lib/utils/synapseTypes/Evaluation/index.ts
See https://github.com/facebook/flow/issues/1379
=> Fix type export

src/lib/style/components/_synapse-homepage.scss
https://sagebionetworks.jira.com/browse/SWC-5346
=> SWC-5346: Shrink mobile Synapse homepage images by about 25%

src/lib/containers/SynapseHomepage.tsx, src/lib/style/components/_synapse-homepage.scss
https://sagebionetworks.jira.com/browse/SWC-5350
=> SWC-5350: Headline style updates on mobile

src/lib/style/bootstrap4_backports/_overrides.scss, src/lib/style/components/_synapse-homepage.scss, src/lib/utils/hooks/useShowDesktop.ts
Also use sass variables for breakpoints for consistency
=> SWC-5353: Buttons need more vertical padding in mobile

src/lib/style/components/_project-view-card.scss
https://sagebionetworks.jira.com/browse/PORTALS-1786
=> PORTALS-1786: Use object-fit to scale down + keep aspect ratio

src/__tests__/lib/containers/personal_access_token/CreateAccessTokenModal.test.tsx, src/lib/containers/personal_access_token/CreateAccessTokenModal.tsx, src/lib/style/components/_personal-access-tokens.scss
Token permissions should behave like links (no underline, added help cursor for clarity): https://sagebionetworks.jira.com/browse/SWC-5331
Pressing enter shouldn't reload page in SWC. This is fixed by using the React-Bootstrap form tag. https://sagebionetworks.jira.com/browse/SWC-5364
=> SWC-5331 and SWC-5356

src/lib/containers/UserCardMedium.tsx
Depends on https://github.com/Sage-Bionetworks/SynapseWebClient/pull/4491
=> PORTALS-1787: Add drop shadow to UserCardMedium

src/lib/containers/IconSvg.md, src/lib/containers/IconSvg.tsx
1. Move table tag out of p tag
2. Fix multiple render warning from styled-components.
=> PORTALS-1783: Fix console log warning

src/lib/containers/CardContainerLogic.tsx
Fix missing type error when updating a portal config.
=> PORTALS-1783: Add back missing type for portals

package.json, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/row_renderers/utils/CardFooter.tsx
Add an option to change where the svg icons are located.
=> PORTALS-1783: Add custom icon path

src/__tests__/lib/containers/MarkdownSynapse.test.tsx, src/demo/containers/playground/ButtonDemo.tsx, src/demo/containers/playground/ColorPaletteInspector.md, src/demo/containers/playground/ColorPaletteInspector.tsx, src/lib/assets/icons/IconMinus.tsx, src/lib/assets/icons/IconPlus.tsx, src/lib/assets/icons/icon_minus.svg, src/lib/assets/icons/icon_plus.svg, src/lib/containers/CardContainer.tsx, src/lib/containers/MarkdownSynapse.tsx, src/lib/containers/home_page/featured-data/FeaturedDataTabs.tsx, src/lib/containers/row_renderers/Dataset.tsx, src/lib/containers/row_renderers/Funder.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/query-filter/FacetFilterHeader.tsx, src/lib/style/base/_icons.scss, src/lib/style/bootstrap4_backports/_base-import.scss, src/lib/style/components/_cards.scss, src/lib/style/components/_featured-data-tabs.scss, src/lib/template_style/_theme.scss
=> PORTALS-1593

src/lib/containers/Login.tsx
https://sagebionetworks.jira.com/browse/SWC-5363
=> SWC-5363 // Make the login fields required

src/lib/containers/home_page/featured-data/FacetPlotsCard.tsx, src/lib/containers/home_page/featured-data/FeaturedDataTabs.md, src/lib/containers/home_page/featured-data/QueryPerFacetPlotsCard.tsx, src/lib/containers/home_page/featured-data/SingleQueryFacetPlotsCards.tsx, src/lib/style/components/_facet-plots-card.scss
(in addition to card titles) in FeaturedDataTabs
=> PORTALS-1835: ability to set card descriptions

src/lib/style/base/_core.scss
targeted using their main-svg class
=> PORTALS-1838: override overflow behavior for plotly js svg element

src/__tests__/lib/containers/personal_access_token/AccessTokenCard.test.tsx, src/__tests__/lib/containers/personal_access_token/AccessTokenPage.test.tsx, src/__tests__/lib/containers/personal_access_token/CreateAccessTokenModal.test.tsx, src/lib/containers/personal_access_token/AccessTokenCard.tsx, src/lib/containers/personal_access_token/AccessTokenPage.tsx, src/lib/containers/personal_access_token/CreateAccessTokenModal.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/style/components/_personal-access-tokens.scss
=> Precheck view and note the programmatic req

src/lib/containers/HeaderCard.tsx, src/lib/style/components/_cards.scss
Header version fo the Generic Card is no longer in a container-fluid.
And set a few max-widths
=> PORTALS-1853

src/__tests__/lib/containers/DirectDownload.test.tsx, src/__tests__/lib/containers/SynapseTable.test.tsx, src/lib/containers/DirectDownload.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/synapse_table_functions/renderTableCell.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/style/base/_core.scss
=> SWC-5388: Replace column value with table entity file download link

src/__tests__/lib/containers/EntityIdList.test.tsx, src/__tests__/lib/containers/SynapseTable.test.tsx, src/lib/containers/EntityIdList.tsx, src/lib/containers/synapse_table_functions/renderTableCell.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/synapseTypes/Table/SelectColumn.ts
=> Portals-1490: Render entity names instead of ids

src/__tests__/lib/containers/UserCardTests.test.tsx, src/lib/containers/Avatar.tsx, src/lib/containers/UserCard.md, src/lib/containers/UserCard.tsx, src/lib/containers/UserCardMedium.tsx, src/lib/utils/SynapseConstants.ts, styleguide.setup.js
=> PORTALS-1902: Add avatar component

src/__tests__/lib/containers/entity_finder/details/DetailsViewRow.test.tsx, src/lib/assets/icons/Arrow.tsx, src/lib/containers/Carousel.tsx, src/lib/containers/UserCardMedium.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/SelectionPane.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/details/view/DetailsViewRow.tsx, src/lib/containers/entity_finder/tree/TreeNode.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_carousel.scss, src/lib/style/components/entity_finder/_breadcrumbs.scss, src/lib/style/components/entity_finder/_details-view.scss, src/lib/style/components/entity_finder/_entity-finder.scss, src/lib/style/components/entity_finder/_tree-node-browse.scss, src/lib/style/components/entity_finder/_tree-node-select.scss, src/lib/style/components/entity_finder/_tree-view.scss
Way too many small changes to describe here. See EntityFinder at https://nickgros.com/Synapse-React-Client/
=> Many Entity Finder improvements

src/__tests__/lib/containers/entity_finder/EntityFinder.test.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/SelectionPane.tsx, src/lib/style/components/entity_finder/_entity-finder.scss
Entity Finder:
* [SWC-5537](https://sagebionetworks.jira.com/browse/SWC-5537): Search box `X` button should clear the input box and results but not close the search pane (the button should still close the search pane).
* [SWC-5557](https://sagebionetworks.jira.com/browse/SWC-5557): Title of the selection pane should be `h4`
=> SWC-5557, SWC-5537

src/__tests__/lib/containers/UserCardTests.test.tsx, src/demo/containers/playground/ButtonDemo.tsx, src/lib/containers/UserCardSmall.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/tree/TreeNode.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/entity_finder/_details-view.scss, src/lib/style/components/entity_finder/_entity-finder.scss, src/lib/style/components/entity_finder/_tree-node-browse.scss, src/lib/style/components/entity_finder/_tree-node-select.scss, src/lib/style/components/entity_finder/_tree-view.scss
Mostly style changes, you can see them in action [here](https://nickgros.com/Synapse-React-Client/#!/Other%20Components/EntityFinder)
=> Entity Finder QA Fixes

src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_query-wrapper-plot-nav.scss, src/lib/style/components/_total-query-results.scss
https://sagebionetworks.jira.com/browse/PORTALS-1820
=> PORTALS-1820

package.json, src/lib/index.ts
Export ExperimentalMode component
=> Release 1.15.97

package.json, src/lib/containers/ExperimentalMode.tsx, src/lib/index.ts
=> Release 1.15.98

src/lib/containers/ExperimentalMode.tsx, src/lib/style/components/_all.scss, src/lib/style/components/_experimental-mode.scss
=> PORTALS-1924: Add popover to experimental mode link

package.json, src/lib/style/components/_access-requirement-list.scss
Remove some extra padding within the modal and add back padding in the modal header.
=> PORTALS-1840: Add component specific css fixes

src/__tests__/lib/containers/download_list_v2/DownloadListTableV2.test.tsx, src/lib/containers/download_list_v2/DownloadListTableV2.tsx, src/lib/utils/hooks/SynapseAPI/useGetAvailableFilesToDownload.ts, src/lib/utils/synapseTypes/DownloadListV2/DownloadListQueryResponse.ts
works with the staging synapse backend (version 359)
=> PLFM-6738: fix typo

src/lib/containers/SearchV2.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/utils/synapseTypes/Table/QueryFilter.ts
Use the new HAS_LIKE functiionality
=> PORTALS-1934

src/lib/containers/UserSearchBox.tsx, src/lib/style/components/_access-requirement-list.scss
=> PORTALS-1931: Add placeholder text and fix alignment issue

src/__tests__/lib/containers/entity/metadata/AnnotationsTable.test.tsx, src/__tests__/lib/containers/entity/metadata/EntityModal.test.tsx, src/__tests__/lib/containers/entity/metadata/MetadataTable.test.tsx, src/lib/containers/entity/metadata/AnnotationsTable.tsx, src/lib/containers/entity/metadata/EntityModal.md, src/lib/containers/entity/metadata/EntityModal.tsx, src/lib/containers/entity/metadata/MetadataTable.tsx, src/lib/style/abstracts/_mixins.scss, src/lib/style/bootstrap4_backports/_overrides.scss, src/lib/style/components/_all.scss, src/lib/style/components/_entity-metadata.scss, src/lib/utils/functions/FileHandleUtils.ts, src/lib/utils/hooks/SynapseAPI/useEntityBundle.ts, src/lib/utils/hooks/SynapseAPI/useSchema.ts, src/lib/utils/synapseTypes/Schema/JsonSchemaObjectBinding.ts, src/mocks/entity/mockEntity.ts, src/mocks/msw/handlers.ts
Depends on #1079 
Metadata tab
Annotations tab, experimental mode off
Annotations tab, experimental mode on. The schema shows up.
The link just points to the raw json file
=> SWC-5620 - Entity Metadata modal

src/lib/utils/hooks/SynapseAPI/useUserBundle.ts
Didn't disable a sub-query on accident
=> Fix undefined error logs in UserCard

package.json, src/lib/containers/IconSvg.tsx, src/lib/containers/row_renderers/utils/CardFooter.tsx, src/lib/style/base/_core.scss
Fix a small UI bug that was discovered after pulling into portals.
=> Release 2.0.15

package.json, src/lib/containers/download_list/DownloadConfirmation.tsx
These are the two use cases, now integration tested in SWC
=> SWC-5664: separate parent container param from query request

src/__tests__/lib/containers/widgets/Checkbox.test.tsx, src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/RadioGroup.test.tsx, src/__tests__/lib/containers/widgets/RangeFacetFilter.test.tsx, src/__tests__/lib/utils/SynapseClient.test.tsx, src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss, src/lib/template_style/_form.scss
Fixing custom styling for checkboxes and radio groups.
Using our custom components:
Synapse Form:
QueryWrapperPlotNav:
=> PORTALS-1970

src/__tests__/lib/utils/SynapseClient.test.tsx, src/lib/containers/UserCard.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/functions/getUserData.ts, src/lib/utils/hooks/useGetInfoFromIds.ts
preview pictures only, as needed
=> SWC-5675: load profile pictures on-the-fly

package.json, src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccess.tsx
1. Bump version for multiple bug fixes for Managed ACT access requirement. 
2. Remove extra $ sign
=> PORTALS-1986: Remove extra $ sign from error message

src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx, src/lib/style/components/_access-requirement-list.scss
Small layout issue and create unique radio group ids
=> Managed ACT Access Requirement: Renewal radio button bug fixes

package.json, src/__tests__/lib/containers/MarkdownSynapse.test.tsx, src/lib/containers/widgets/SynapseVideo.md, src/lib/containers/widgets/SynapseVideo.tsx
1. For external videos, remove login
2. Rename vars to distinguish videos with synapse pre-signed URLs or external URLs.
=> AG-178: Remove login for external video

src/lib/style/components/_annotations.scss
=> SWC-5703 - Properly arrange datetime widget in array grid

src/lib/assets/skeletons/SkeletonButton.tsx, src/lib/assets/skeletons/SkeletonTable.tsx, src/lib/containers/entity/metadata/AnnotationsTable.tsx, src/lib/containers/entity/metadata/EntityModal.tsx, src/lib/style/bootstrap4_backports/_overrides.scss, src/lib/style/components/_all.scss, src/lib/style/components/_entity-metadata.scss, src/lib/style/components/_skeletons.scss
=> Create SkeletonTable, make skeletons less placeholder-y

src/__tests__/lib/containers/entity/annotations/AdditionalPropertiesSchemaField.test.ts, src/lib/containers/entity/annotations/AdditionalPropertiesSchemaField.tsx, src/lib/containers/entity/annotations/CustomTextWidget.tsx, src/lib/containers/entity/annotations/SchemaDrivenAnnotationEditor.tsx
Fixes [SWC-5757](https://sagebionetworks.jira.com/browse/SWC-5757) and [SWC-5758](https://sagebionetworks.jira.com/browse/SWC-5758)
=> SWC-5757, SWC-5758

src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx
This is caused by not being able to add the current user when creating a new AR.
=> PORTALS-1991 & SWC-5765: Duplicate accessors bug

package.json, src/lib/style/components/_user-profile-links.scss
=> SWC-5771: do not explicitly set the user links panel width 

src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx
[Jira](https://sagebionetworks.jira.com/browse/PORTALS-2014)
Not sure why event propagation was preventing this dropdown from opening (portals only, not in SRC demo)
=> PORTALS-2014

src/lib/containers/table/SynapseTable.tsx
Download column wasn't hiding otherwise
=> PORTALS-2002 - Don't show AddToDLColumn if hideDownload

src/lib/containers/access_requirement_list/AccessRequirementList.tsx
Not sure why this code was here, but this feature is outside of experimental mode (we should not reset the step).
=> SWC-5794: Access Requirement list step was being reset

src/lib/containers/SubsectionRowRenderer.tsx, src/lib/containers/UserCardListRotate.tsx
NoCheck since some params are optional
=> PORTALS-2046: deep compare new and old prop values

package.json, src/lib/containers/PlotlyWrapper.tsx
Needed for responsive plots in Agora
=> Add `useResizeHandler` prop to our PlotlyWrapper

src/lib/utils/SynapseClient.ts
Just need to specify a couple of types
=> Fix docs build

src/lib/containers/QueryCount.tsx, src/lib/containers/home_page/goals/Goals.Desktop.tsx, src/lib/containers/home_page/goals/Goals.Mobile.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/table/StandaloneQueryWrapper.tsx, src/lib/containers/table/TopLevelControls.tsx
=> PORTALS-2060: ability to hide the query count

src/lib/containers/DirectDownload.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/download_list_v2/DownloadCartPage.tsx, src/lib/containers/download_list_v2/DownloadListTable.tsx, src/lib/style/abstracts/_mixins.scss, src/lib/style/bootstrap4_backports/_overrides.scss, src/lib/style/components/_download-list-v2.scss
[SWC-5874](https://sagebionetworks.jira.com/browse/SWC-5874): Go to Download List directly if there are no access issues.
[SWC-5869](https://sagebionetworks.jira.com/browse/SWC-5869) : Actions panel, and reusable mixin for this type of sticky column for other tables.
=> SWC-5874, SWC-5869

src/lib/containers/FileUpload.tsx, src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx
If there's a file upload error while gaining access, show it
=> PORTALS-2078

src/lib/containers/ToastMessage.tsx
https://sagebionetworks.jira.com/browse/SWC-5900?focusedCommentId=138758
=> SWC-5900: fix too much recursion error

package.json, src/lib/umd.index.ts
Supports SWC-5928: Sage-Bionetworks/SynapseWebClient#4761
=> Add SkeletonButton to the UMD bundle

src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/demo/containers/playground/ButtonDemo.tsx, src/demo/containers/playground/ToastDemo.tsx, src/lib/containers/FullWidthAlert.md, src/lib/containers/FullWidthAlert.tsx, src/lib/containers/ToastMessage.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx, src/lib/containers/table/datasets/DatasetItemsEditor.tsx, src/lib/style/abstracts/_mixins.scss, src/lib/style/bootstrap4_backports/_base-import.scss
- Change `FullWidthAlert`/`displayToast` signatures
- Add disable, tooltip options
- Now uses a new `AlertButtonConfig` type
- Add "tertiary" button style that matches our `<a>` tags stylistically
https://user-images.githubusercontent.com/17580037/150217703-6868275e-1fdf-4cc0-a235-bad1bc40a4dc.mov
Before/After using border-bottom vs text-decoration-offset:
Before:
https://user-images.githubusercontent.com/17580037/150364431-cb938f38-e5ac-4f31-a49f-7de1ea067710.mov
After:
https://user-images.githubusercontent.com/17580037/150364436-3aacc998-a09d-4932-aa8d-776fce99339c.mov
=> Changes to support SWC-5872

package.json
- [SWC-5935](https://sagebionetworks.jira.com/browse/SWC-5935)
=> Release version 2.1.7

src/lib/style/components/_global-alert.scss
Slight appearance tweak to FullWidthAlert for [SWC-5942](https://sagebionetworks.jira.com/browse/SWC-5942)
https://user-images.githubusercontent.com/17580037/153888765-72c0b40b-5301-4697-8ad5-c141781824b8.mov
=> SWC-5942: Remove max-width for messageArea

src/lib/containers/EntityIcon.tsx, src/lib/style/components/_global-alert.scss, src/lib/style/components/_query-wrapper-plot-nav.scss, src/lib/style/components/_synapse-nav-drawer.scss, src/lib/utils/synapseTypes/EntityType.ts
and a couple of small spacing issues in SWC
=> SWC-5991: to support new materialized view entity type

package.json, src/__tests__/lib/containers/entity/metadata/EntityModal.test.tsx, src/lib/containers/ErrorBanner.tsx, src/lib/containers/JiraIssueCollector.tsx, src/lib/containers/StyleGuidistComponentWrapper.tsx, src/lib/containers/entity/annotations/SchemaDrivenAnnotationEditor.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/SynapseContext.tsx, src/lib/utils/hooks/SynapseAPI/useUserBundle.ts, src/lib/utils/synapseTypes/UserProfile.ts, styleguide.config.js, yarn.lock
If our ErrorBoundary catches a 500 error, we should show our Jira issue collector.
https://user-images.githubusercontent.com/17580037/156203837-248882a5-fd1f-4977-a56c-f52891a141b9.mov
=> SWC-5809 - Add Jira issue collector to Error Boundary

src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/details/view/DetailsViewTableRenderers.tsx
* Ability to change "Always Latest Version" text
* Don't show the "Always Latest Version" tooltip when the option isn't present.
=> SWC-5883 and SWC-6022

src/lib/containers/QueryWrapper.tsx, src/lib/containers/home_page/featured-data/QueryPerFacetPlotsCard.tsx, src/lib/containers/home_page/featured-data/SingleQueryFacetPlotsCards.tsx, src/lib/containers/table/StandaloneQueryWrapper.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx, src/lib/utils/functions/unCamelCase.ts, src/lib/utils/synapseTypes/Table/AsynchronousJobStatus.ts, src/lib/utils/synapseTypes/Table/FacetColumnRequest.ts, src/lib/utils/synapseTypes/Table/FacetColumnResult.ts, src/lib/utils/synapseTypes/Table/QueryResultBundle.ts
* Improve various type definitions across SRC
* Prettier code formatting in modified files
=> Type fixes/formatting

package.json, src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/utils/SynapseClient.ts
Fixes [SWC-6086](https://sagebionetworks.jira.com/browse/SWC-6086)
=> Release v3.0.2

src/lib/containers/FullTextSearch.tsx, src/lib/containers/SearchV2.tsx, src/lib/containers/SqlEditor.tsx, src/lib/style/components/_query-wrapper-plot-nav.scss, src/lib/style/components/_query-wrapper-text-input.scss
sql editor was stealing all the click events
=> PORTALS-2163: fix overlapping components

src/__tests__/lib/containers/table/datasets/DatasetItemsEditor.test.tsx, src/lib/containers/table/datasets/DatasetDisplayConstants.ts, src/lib/containers/table/datasets/DatasetItemsEditor.tsx
=> SWC-6008 - update dataset editor copy

src/lib/containers/CardContainer.tsx, src/lib/containers/GenericCard.tsx
=> SWC-6115: special renderer for the currentVersion if is view

src/__tests__/lib/containers/dataaccess/AccessRequirementSearchBox.test.tsx, src/lib/containers/dataaccess/AccessRequirementSearchBox.md, src/lib/containers/dataaccess/AccessRequirementSearchBox.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/functions/getEndpoint.ts, src/lib/utils/hooks/SynapseAPI/dataaccess/useGetAccessRequirement.ts, src/lib/utils/synapseTypes/AccessRequirement/AccessRequirementSearch.ts, src/mocks/mockAccessRequirements.ts
Searching ARs:
https://user-images.githubusercontent.com/17580037/170099659-7f4719fb-5803-4c58-89cb-3e29bc844695.mov
Initial AR:
https://user-images.githubusercontent.com/17580037/170121232-1269dbfa-85b5-4492-b0e9-6820439bf032.mov
Enter AR ID:
https://user-images.githubusercontent.com/17580037/170121352-6fc39481-e7d0-4a19-ba32-a80b4763bd5c.mov
=> SWC-6123 - Access Requirement Search Box

src/__tests__/lib/containers/SynapseTable.test.tsx, src/lib/containers/AddToDownloadListV2.tsx, src/lib/containers/synapse_table_functions/SynapseTableCell.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/functions/queryUtils.ts, src/lib/utils/synapseTypes/Table/QueryResult.ts
From [Jira](https://sagebionetworks.jira.com/browse/SWC-6137):
* Fix issue where download column would appear when SQL includes DISTINCT
* Fix issue where Add to Download Cart component wouldn't appear in Datasets
Additionally:
* Fix issue where Access column wouldn't appear for datasets
=> SWC-6137 - Fix SynapseTable download column issues

src/lib/containers/FullTextSearch.tsx, src/lib/containers/SearchV2.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.md, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/table/StandaloneQueryWrapper.tsx, src/lib/style/components/_query-wrapper-text-input.scss
=> PORTALS-2176

src/lib/style/components/_synapse-homepage.scss
…  (instead of maintaining a 3x3 grid on large screens)
=> SWX-6136: fix Powered By Synapse section breakpoint that causes a row with 4 items

src/lib/containers/EntityIdList.tsx, src/lib/containers/EntityLink.tsx, src/lib/containers/dataaccess/AccessRequirementTable.tsx, src/lib/containers/synapse_table_functions/SynapseTableCell.tsx, src/lib/style/components/_governance-dashboard.scss
=> Show ID in AR table

package.json, src/lib/containers/QueryWrapper.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/umd.index.ts, src/lib/utils/hooks/SynapseAPI/entity/useGetQueryResultBundle.ts, yarn.lock
Mostly reducing the frequency of table query requests. This doesn't fix the main bug described in SWC-6162. The real bug is in SWC, so these changes are fine to go in develop.
=> SWC-6162 - Optimize QueryWrapper, include version in bundle

src/lib/containers/StackChanger.md, src/lib/containers/StackChanger.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/SynapseConstants.ts, src/lib/utils/functions/getEndpoint.ts, styleguide.config.js, styleguide.setup.js
=> Add StackChanger to Styleguidist

src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/__tests__/lib/containers/entity_finder/tree/EntityTree.test.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/Login.md, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/details/view/DetailsViewTableRenderers.tsx, src/lib/containers/entity_finder/tree/EntityTree.tsx, src/lib/style/components/_entity-badge.scss, src/lib/style/components/entity_finder/_details-view.scss, src/lib/style/components/entity_finder/_entity-finder.scss, src/lib/style/components/entity_finder/_selection-pane.scss, src/mocks/entity/mockEntity.ts
https://user-images.githubusercontent.com/17580037/174118347-6f81ac12-2750-4ef1-b1e1-1e30e279ddf6.mov
=> SWC-6028 - Entity Finder table navigation

src/__tests__/lib/containers/EntityBadgeIcons.test.tsx, src/lib/containers/EntityBadgeIcons.tsx, src/lib/style/components/_entity-badge.scss, src/lib/utils/hooks/SynapseAPI/entity/queryKeys.ts, src/lib/utils/hooks/SynapseAPI/entity/useEntity.ts, src/lib/utils/hooks/useGetInfoFromIds.ts
Small refinements to prepare for use in SWC
=> SWC-5647 - Entity Badge Icons

src/__tests__/lib/containers/dataaccess/AccessHistoryDashboard.test.tsx, src/lib/containers/UserSearchBoxV2.tsx, src/lib/containers/dataaccess/AccessHistoryDashboard.tsx, src/lib/containers/dataaccess/AccessRequirementDashboard.tsx, src/lib/containers/dataaccess/AccessRequirementSearchBox.tsx, src/lib/containers/dataaccess/AccessSubmissionDashboard.tsx
Test has been sporadically failing across multiple builds
=> Attempt to fix AccessHistoryDashboard.test

src/lib/style/components/entity_finder/_details-view.scss, src/lib/style/components/entity_finder/_tree-view.scss
https://user-images.githubusercontent.com/17580037/178763702-99e4bab7-a5ff-48db-9fa7-e497782251d9.mov
=> SWC-6197 - Fix missing cursor: pointer in Entity Finder

.storybook/preview.jsx, package.json, yarn.lock
I recently used it to track down the cause of an issue, could be useful to have
=> Add why-did-you-render to storybook

src/lib/containers/EntityIcon.tsx
Enables https://sagebionetworks.jira.com/browse/SWC-6242
=> Allow disabling tooltip for EntityIcon

src/__tests__/lib/containers/table/datasets/DatasetItemsEditor.test.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/table/datasets/DatasetItemsEditor.tsx, src/lib/utils/functions/EntityTypeUtils.ts, src/lib/utils/synapseTypes/Table/Dataset.ts, src/lib/utils/synapseTypes/VersionInfo.ts, src/mocks/entity/index.ts, src/mocks/entity/mockDataset.ts, src/mocks/entity/mockDatasetCollection.ts
SWC-6198 - Start the Entity Finder in the current project
SWC-6214 - Support for Dataset Collections
=> SWC-6198, SWC-6214 - Dataset Editor changes

src/__tests__/lib/containers/dataaccess/AccessHistoryDashboard.test.tsx, src/lib/containers/CopyToClipboardInput.tsx, src/lib/containers/Login.stories.tsx, src/lib/containers/StyleGuidistComponentWrapper.tsx, src/lib/containers/personal_access_token/AccessTokenPage.tsx, src/lib/containers/personal_access_token/CreateAccessTokenModal.tsx, src/lib/containers/synapse_form_wrapper/SynapseFormWrapper.stories.tsx, src/lib/style/components/_copy-to-clipboard.scss, src/lib/utils/SynapseClient.ts, src/lib/utils/hooks/SynapseAPI/user/usePersonalAccessToken.ts
Failure in AccessHistoryDashboard: https://app.travis-ci.com/github/Sage-Bionetworks/Synapse-React-Client/builds/253426839
Failure in AccessTokenPage: https://app.travis-ci.com/github/Sage-Bionetworks/Synapse-React-Client/builds/253472852
Also made minor updates to styling in AccessTokenPage
Made authentication token acquisition more robust in storybook
=> Fix flaky tests, AccessTokenPage styling, Storybook auth issues

src/__tests__/lib/containers/UserSearchBoxV2.test.tsx, src/__tests__/lib/containers/dataaccess/AccessHistoryDashboard.test.tsx, src/__tests__/lib/containers/dataaccess/AccessRequirementDashboard.test.tsx, src/__tests__/lib/containers/dataaccess/AccessSubmissionDashboard.test.tsx
=> Always await selectEvent

src/lib/containers/entity_finder/tree/VirtualizedTree.tsx, src/lib/style/components/entity_finder/_tree-node-browse.scss
=> SWC-6060: Increase caret size

src/__tests__/lib/containers/entity_finder/tree/VirtualizedTree.test.tsx, src/lib/containers/entity_finder/tree/VirtualizedTree.tsx
Dual-pane:
https://user-images.githubusercontent.com/17580037/184215040-9f916aa9-3652-48ea-8b4a-4251c1e70f8a.mov
Single-pane:
https://user-images.githubusercontent.com/17580037/184215144-a23bd93a-585f-4d27-9c97-ed8607e6a2d5.mov
=> SWC-5961: Show tooltip in Entity Tree

src/lib/containers/table/EntityIDColumnCopyIcon.tsx, src/lib/utils/SynapseClient.ts
Abort starting new queries if component is unmounted
=> PORTALS-2296

src/lib/containers/entity_finder/details/view/DetailsViewTableRenderers.tsx
=> SWC-6077: Show the latest version text if there are no options

src/lib/style/components/_total-query-results.scss
=> PORTALS-2303, PORTALS-2304, PORTALS-2305

src/lib/style/components/_query-wrapper-plot-nav.scss
=> PORTALS-2302: add background shade in facets area

src/lib/containers/table/StandaloneQueryWrapper.tsx
- Change default NoContentPlaceholderType for StandaloneQueryWrapper
=> PORTALS-215: Update default `noContentPlaceholderType` for StandaloneQueryWrapper

src/lib/containers/entity/page/breadcrumbs/EntityPageBreadcrumb.stories.tsx, src/lib/containers/entity/page/breadcrumbs/EntityPageBreadcrumbs.tsx, src/lib/style/base/_core.scss, src/lib/umd.index.ts, src/lib/utils/functions/StringUtils.ts, src/lib/utils/theme/DefaultTheme.ts, src/lib/utils/theme/typography/Link.ts, src/setupTests.js
- Add EntityPageBreadcrumbs
- Don't apply CSS link styling to MUI Links
- Apply link styling to MUI Link component using default theme
https://user-images.githubusercontent.com/17580037/200328560-f6d15966-7b38-4e4a-8d25-491ff3ee57e0.mov
=> SWC-6312: EntityPageBreadcrumbs

.github/workflows/npmpublish.yml
Breaks release; we should add a dry-run
=> Revert #1805

package.json, src/lib/containers/markdown/MarkdownSynapse.stories.tsx
and add a story to MarkdownSynapse
=> bump SRC to 3.1.12

.storybook/main.ts, .storybook/preview.jsx, package.json, public/mockServiceWorker.js, src/lib/containers/StackChanger.tsx, src/lib/containers/StorybookComponentWrapper.tsx, src/lib/containers/dataaccess/SubmissionPage.stories.tsx, src/mocks/msw/handlers.ts, src/mocks/msw/handlers/entityHandlers.ts, src/mocks/msw/handlers/userProfileHandlers.ts, yarn.lock
- Add msw-storybook-addon
- Add mocked story for the SubmissionPage
I decided to add this Storybook addon because it is generally useful to be able to inspect these components without looking at real data.
I chose to do it now because I want to make theme-wide changes to Typography (removing top margins from always being applied), and one component that will be most affected is the SubmissionPage component
=> SWC-6323: Add msw-storybook-addon

src/__tests__/lib/containers/menu/DropdownMenu.test.tsx, src/lib/containers/menu/DropdownMenu.stories.tsx, src/lib/containers/menu/DropdownMenu.tsx
https://user-images.githubusercontent.com/17580037/202484591-38df024a-fde5-495a-a8f8-38a47f4f4dc8.mov
Thanks to MUI it also has keyboard navigation
=> SWC-6323: Add generic DropdownMenu component

src/__tests__/lib/containers/entity/page/EntityActionMenu.test.tsx, src/lib/containers/entity/page/action_menu/EntityActionMenu.stories.tsx, src/lib/containers/entity/page/action_menu/EntityActionMenu.tsx, src/lib/umd.index.ts
- Add EntityActionMenu component
https://user-images.githubusercontent.com/17580037/204376609-758c0e1e-6a41-4cdd-a6b0-6be979bb3efe.mov
=> SWC-6323: Add EntityActionMenu component

.storybook/main.ts, src/lib/containers/entity/page/breadcrumbs/EntityPageBreadcrumbs.tsx, src/lib/containers/menu/DropdownMenu.tsx
- Fix z-index conflict between MUI dropdown and react-flow provenance graph
- Breadcrumb style changes
- Add msw-storybook-addon to optimizeDeps
=> SWC-6321: Small fixes + style changes

src/lib/containers/markdown/MarkdownEditor.tsx, src/lib/containers/markdown/MarkdownWidget.tsx, src/lib/containers/markdown/UserMentionModal.tsx, src/lib/containers/markdown/widget/MarkdownUserBadge.tsx, src/lib/containers/markdown/widget/MarkdownUserOrTeamBadge.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/hooks/SynapseAPI/user/useUserGroupHeader.ts, src/lib/utils/synapseTypes/UserGroupHeader.ts
Allow SynapseMarkdown to identify if tagged alias is a user or team and render badge accordingly.
=> PORTALS-2393: Able to tag team in Markdown Editor

src/__tests__/lib/containers/entity/page/EntityActionMenu.test.tsx, src/__tests__/lib/containers/menu/ComplexMenu.test.tsx, src/lib/containers/entity/page/action_menu/EntityActionMenu.tsx, src/lib/containers/menu/ComplexMenu.tsx, src/lib/containers/menu/DropdownMenu.tsx
- Pass `disabled` through to IconButton
- Specify flex alignItems
- Move dropdown tooltip placement
=> SWC-6321: Allow disabled IconButton

src/lib/containers/IconSvg.tsx, src/lib/containers/Login.stories.tsx, src/lib/containers/Login.tsx, src/lib/containers/LoginPage.tsx, src/lib/style/components/_login.scss
https://user-images.githubusercontent.com/60489495/205351711-aba567fb-2773-47cf-8d4b-d5df02e66b37.mov
Updated arrow location
Mobile view
Login component
=> PORTALS-2422: separate email sign-in for logging in

.github/workflows/build-docs.yml, .storybook/main.ts, src/lib/containers/dataaccess/SubmissionPage.stories.tsx
- Fix imports in SubmissionPage.stories.tsx
- Additional configuration for docgen in .storybook/main.ts
- Add docs build action to PR
=> Storybook improvements - Add some forgotten changes that broke the build

src/__tests__/lib/containers/CopyToClipboardInput.test.tsx, src/__tests__/lib/containers/CopyToClipboardString.test.tsx, src/_tests_/lib/containers/access_requirements/AddConditionsForUseButton.test.tsx, src/_tests_/lib/containers/entity/page/title_bar/EntityTitleBarVersionInfo.test.tsx, src/lib/containers/CopyToClipboardInput.tsx, src/lib/containers/CopyToClipboardString.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/access_requirements/AddConditionsForUseButton.stories.tsx, src/lib/containers/access_requirements/AddConditionsForUseButton.tsx, src/lib/containers/access_requirements/HasAccess.stories.tsx, src/lib/containers/access_requirements/HasAccessV2.tsx, src/lib/containers/dataaccess/AccessRequirementSearchBox.stories.tsx, src/lib/containers/dataaccess/ReviewerDashboard.stories.tsx, src/lib/containers/dataaccess/SubmissionPage.stories.tsx, src/lib/containers/entity/page/title_bar/EntityTitleBarVersionInfo.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/hooks/SynapseAPI/team/useTeamMembers.ts, src/lib/utils/hooks/SynapseAPI/user/useUserBundle.ts, src/mocks/entity/mockFileEntity.ts
- Add CopyToClipboardString
- Add AddConditionsForUseButton
- Add EntityTitleBarVersionInfo
- Move Governance stories from Synapse/Governance to Governance/
=> SWC-6318: More components used within new title bar

src/lib/containers/access_requirement_list/AccessRequirementList.stories.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/mocks/mockAccessRequirements.ts, src/mocks/mockWiki.ts, src/mocks/msw/handlers.ts, src/mocks/msw/handlers/accessRequirementHandlers.ts, src/mocks/msw/handlers/entityHandlers.ts, src/mocks/msw/handlers/userProfileHandlers.ts, src/mocks/msw/handlers/wikiHandlers.ts
- Add stories, and many handlers to support them
https://user-images.githubusercontent.com/17580037/211075895-6eea3405-29bc-46b5-9c19-cd3411c04588.mov
=> PORTALS-2459: Add stories for AccessRequirementList

src/__tests__/lib/containers/QueryVisualizationWrapper.test.tsx, src/__tests__/lib/containers/entity/page/title_bar/EntityTitleBarVersionInfo.test.tsx, src/__tests__/lib/containers/provenance/ProvenanceGraph.test.tsx, src/__tests__/lib/containers/table/table-top/DownloadOptions.test.tsx, src/lib/containers/entity/page/CreatedByModifiedBy.stories.tsx, src/lib/containers/entity/page/CreatedByModifiedBy.test.tsx, src/lib/containers/entity/page/CreatedByModifiedBy.tsx, src/lib/umd.index.ts, src/mocks/entity/index.ts, src/mocks/entity/mockDataset.ts, src/mocks/entity/mockEntity.ts, src/mocks/entity/mockFileEntity.ts, src/mocks/entity/mockTableEntity.ts, src/mocks/mockQueryResponseDataWithManyEnumFacets.ts, src/mocks/provenance/mockActivity.ts
- Add CreatedByModifiedBy component
- Restructure and add mock data for testing
=> SWC-6349: New component for showing entity created/modified by
