src/demo/containers/playground/UserCardDemo.tsx, src/lib/style/Portal.css, src/lib/style/Portal.scss
fiddle with flex-basis based on width to maximize area (tricky with margin).
also update card demo so that it has an odd number, to demo SWC-4765 bug.
=> SWC-4765: set flex grow to 0 so that item does not take up entire row

src/lib/containers/UserCardSmall.tsx
Includes isn't supported in IE11, additionally we no longer user 'TEMPORARY-' in usernames so the check is not needed
=> got rid of includes method 

src/demo/containers/playground/MarkdownSynapseDemo.tsx, src/demo/containers/playground/Playground.tsx, src/lib/containers/MarkdownSynapse.tsx
Fixed bug with click handler in markdown component preventing all default events, also added target  as whitelisted attribute to anchor tag
=> cleaned up event handling with markdown synapse

src/__tests__/lib/containers/drug_upload_tool/DrugUploadForm.test.tsx, src/lib/containers/drug_upload_tool/DrugUploadForm.tsx, src/lib/containers/drug_upload_tool/types.ts, src/mocks/mockDrugToolFormData.json, src/mocks/mockDrugToolFormDataComplexInvalid.json, src/mocks/mockDrugToolFormNavSchema.json, src/mocks/mockDrugToolFormSchema.json, src/mocks/mock_drug_tool_data.ts
This commit allows us to define custom validations i.e. validation beyond of what JSON schema provides.
It relies on [json-rules-engine](https://github.com/CacheControl/json-rules-engine) library which we are already using for conditional navigation between the steps.
The validation rules are defined in the in the preexisting 'navSchema' file which is responsible for navigating between the screens and storing all the configuration beyond that is provided by json-schema forms library
We are adding a single optional property [validationRules]( https://github.com/Sage-Bionetworks/Synapse-React-Client/compare/master...conundrumgirl:develop?expand=1#diff-ccfd60b0048ee2e3e3e2ab501b77a371R9)  to each step.
Before we submit the form we run those rules through the validation engine with the form …
=> feat(DrugTool): add custom validation

src/demo/containers/Demo.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx
1. `enableDownloadConfirmation` prop has to be explicitly set to `true` for new implementation to work
2. added `isGroupedQuery` prop to EllipsisDropdown to hide download for grouped queries
Filter and download icon are  already hidden in table header
=> fix(SRC): hide new download implementation for now

src/lib/containers/CardContainer.tsx, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/HeaderCard.tsx, src/lib/style/Cards.scss
https://sagebionetworks.jira.com/browse/PORTALS-709
Potential solution: 
adding optional  `isAlignToLeftNav` parameter to HeaderCard. 
variant without left nav:
variant with left nav
=> fix(style): Study Page: Header card alignment to page

src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx
Removing file download confirmation for queries which don't have fileView.
getting  `tableId` from `queryResults`, running `getEntity()` on that id and checking the concreteType for `EntityView`
=> fix(SynapseTable): don't show download files unless it's entity view

src/__tests__/lib/containers/Search.test.tsx, src/lib/containers/Search.tsx
Don't change the display text until the next search is made
Focus on input when dropdown selection is changed
=> PORTALS-889

src/__tests__/lib/containers/DownloadLoginModal.test.tsx, src/lib/containers/table/table-top/DownloadLoginModal.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx, src/lib/template_style/_Theme.scss
[PORTALS-970](https://sagebionetworks.jira.com/browse/PORTALS-970)
When downloading files from table, if you are not logged in the menu option is not enabled. User has no idea why. We should handle that case by showing information dialog explaining why its disable and what they can do to remedy that (log in).
=> feat(filedDownload): display modal if user not logged in

src/lib/style/Core.scss
(parent element is not properly wrapping due to the absolute positioning).
=> PORTALS-978: set nav buttons z-index so that they can be clicked on

package.json, src/__tests__/lib/containers/DownloadLoginModal.test.tsx, src/__tests__/lib/containers/QueryWrapper.test.tsx, src/demo/containers/App.tsx, src/lib/containers/Login.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/table/table-top/DownloadLoginModal.tsx, src/lib/utils/SynapseClient.ts, yarn.lock
Added callback functions to synapse client login/sign out functions
Used Universal-Cookie library to replace cookie functions in synapse client
Made it so the portal-side login modal shows up from synapsetable when clicking download files, this is the only way I could have the session callback for the portals get passed in without using a global variable.
=> remove page reload calls and add callbacks

src/__tests__/lib/containers/HasAccess.test.tsx, src/demo/containers/Demo.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/download_list/DownloadListTable.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/SynapseClient.ts, src/mocks/mock_file_handle.ts
- Show Access column if not logged in (may be open data).  If unable to get the FileHandle and not logged in, then indicate user needs to first sign in.
- Distinguish HasAccess being used in a DownloadList vs other contexts.  Only show warnings about being part of a DownloadOrder package if item is in the DownloadList.  Add tests for HasAccess outside of DownloadList.
=> SWC-5052 continued

src/__tests__/lib/containers/HasAccess.test.tsx, src/demo/containers/Demo.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/download_list/DownloadListTable.tsx, src/lib/utils/SynapseClient.ts, src/mocks/mock_folder_entity.ts
Add support to show access for other entity types.   Renamed quite a few variables so that they made more sense to me.  Test a file that was marked as "Open Data" (while anonymous).
=> PORTALS-1033

src/lib/containers/CardContainer.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/QueryCount.tsx, src/lib/containers/QueryWrapperMenu.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/synapseTypes/Table/ColumnModel.ts
Handle rendering multi value secondary labels in card, revert to using selected facets in query wrapper menu
Can see example multi value rendering here in theme label -
=> PORTALS-1082

src/lib/utils/SynapseClient.ts
or checking to see if user has already given consent to this request
=> SWC-5125: must be logged in before presenting the OAuth request description, 

src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/utils/hooks/useGetEntityHeaders.ts
useGetEntityHeaders enters an infinite loop in the /Playground/QueryWrapperPlotNavDemo
Taking `references, data` out of useEffect dependency array fixes the loop. I do *not* understand why `references` affect this. Will investigate farther  but wanted to put in a fix for now
=> fix(PORTALS-1101): fix the infinite loop. Need to understand it better

package.json, src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/__tests__/lib/containers/HasAccess.test.tsx, src/__tests__/lib/containers/download_list/DownloadListTable.test.tsx, src/demo/containers/playground/Playground.tsx, src/demo/containers/playground/QueryWrapperMenuDemo.tsx, src/demo/containers/playground/ShowDownloadDemo.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/UserCardSmall.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx, src/lib/containers/download_list/DownloadDetails.tsx, src/lib/containers/download_list/DownloadListTable.tsx, src/lib/containers/download_list/ShowDownload.tsx, src/lib/index.ts, src/lib/style/base/_core.scss, src/lib/style/base/_helpers.scss, src/lib/style/components/_all.scss, src/lib/style/components/_download-link.scss, src/lib/style/components/_download-list.scss, src/lib/utils/SynapseClient.ts, src/lib/utils/functions/dispatchDownloadListChangeEvent.ts, src/lib/utils/hooks/useGetInfoFromIds.ts, yarn.lock
scenario:
- `componentDidMount()` is called with two functions inside - `asyncCall_1` and `asyncCall_2`
- `asyncCall_1` finishes before `asyncCall_2` and call's `setState`
- `componentDidUpdate` is triggered because of the `setState` call
- `asyncCall_1` and `asyncCall_2` are both called by `componentDidUpdate`
- `asyncCall_2` from the first `componentDidMount` finishes and call's `setState`
- `componentDidUpdate` is called (note - the first `componentDidUpdate` hasn't finished yet..)
-  ... until finally this all stop's because both stop conditions for `asyncCall_1` and `asyncCall_1` are met
- The download list renders as a modal now to support the ShowDownload component,  removed invokeDownloadListUpdatedEvent by calling listUpdatedCallback() directly using typescript conditional …
=> Add DownloadList to Portals

package.json
Yarn isn't recognizing the last published version 1.14.1, republishing to see if that helps.
=> Republish to try and fix broken yarn install

src/__tests__/lib/containers/QueryWrapper.test.tsx, src/__tests__/lib/containers/QueryWrapperMenu.test.tsx, src/demo/containers/Demo.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/QueryWrapperMenu.tsx, src/lib/utils/functions/deepLinkingUtils.ts
https://sagebionetworks.jira.com/browse/PORTALS-1095
I think a good way to test it would be to select a facet on the left and do some filtering. Wait of data to load. Copy the url, paste it into a different tab and see what happens
=> fix(PORTALS-1095): persist query parameters to URL in portals

src/__tests__/lib/containers/TotalQueryResults.test.tsx, src/__tests__/lib/containers/widgets/facet-nav/FacetNavPanel.test.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/Facets.tsx, src/lib/containers/Search.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/FacetFilter.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/style/components/facet_nav/_facet-nav-panel.scss, src/lib/style/components/facet_nav/_facet-nav.scss
- refactor  TotalQueryResults to use hooks
- add filters to the Facet visualizations
lates demo is on [gh-pages](https://conundrumgirl.github.io/Synapse-React-Client/Playground/QueryWrapperPlotNavDemo)
=> PORTALS-1022 - cont.

src/__tests__/lib/containers/widgets/query-filter/QueryFilter.test.tsx, src/lib/containers/QueryWrapperPlotNav.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/query-filter/QueryFilter.tsx
This should allow QueryFilter to work outside of the  SynapseTable functionally (still needs layout work for parent container)
=> fix(QueryFilter): Make query filter do it's own update

src/__tests__/lib/utils/functions/sqlFunctions.test.ts, src/lib/utils/functions/sqlFunctions.ts
or there are no search params.  Also, parser returns DBLSTRINGs from tokenizer, and then fails when attempting to reconstruct the same sql using it's own parser!  Replace all DBLSTRINGs with LITERAL, but I don't think we'll ever get into this situation today because we don't mix the study page conditional with the encoded Query search param.
=> PORTALS-1256: added early exit if search params are QueryWrapper definitions

src/__tests__/lib/containers/QueryWrapperMenu.test.tsx, src/__tests__/lib/containers/widgets/facet-nav/FacetNav.test.tsx, src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/demo/containers/playground/WidgetDemo.tsx, src/lib/containers/EntityLink.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/QueryWrapperMenu.tsx, src/lib/containers/SearchV2.tsx, src/lib/containers/StackedBarChart.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/query_wrapper_plot_nav/FilterAndView.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/query_wrapper_plot_nav/TopLevelControls.tsx, src/lib/containers/synapse_form_wrapper/StepsSideNav.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/ElementWithTooltip.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx, src/lib/style/base/_helpers.scss, src/lib/style/components/_all.scss, src/lib/style/components/_searchv2.scss, src/lib/style/components/_total-query-results.scss, src/lib/utils/functions/sqlFunctions.ts, src/mocks/mock_query_data.tsx
- Refactored QueryWrapperPlotNav to place the top level controls under QueryWrapper, allowing for search and add to download to get implemented
- Added Clear All button
- Add new state variables to QueryWrapper: `searchQuery`, `topLevelControlsState`
- Put in intermediate search component with updated UI -- SearchV2.tsx
Search with dropdown open
Search with selection made (note the chiclet with the search query having been made)
=> Portals 1273

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/SearchV2.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx
- Add back prop `searchable` to SearchV2, prop filters columns to those in the prop, if prop isn't specified it shows all columns
- Also added back filter `isSupportedColumn` on search columns, I missed it but in one the prs today that was accidentally removed
- Removed code that would reset the column and search text on submit
=> PORTALS-1393

src/lib/containers/SearchV2.tsx
didn't filter the columns in the search function, this caused an issue where the column that was searched through was different than the one that was being displayed
=> fix bug with searching the wrong column

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/access_requirement_list/AccessRequirementList.tsx, src/lib/style/base/_core.scss, src/lib/style/components/_access-requirement-list.scss, src/lib/utils/functions/deepLinkingUtils.ts
PORTALS-1425: Needed partMask to include select_columns, otherwise zero results will show up on render when there are search params
PORTALS-1178: Fix is two fold - first the check for the token change, see if it is different from before, also fixed a state variable that wasn't being set properly.
Made a few changes in other components to change their 'did update' to see if the token changes for both sign-in and sign-out, before it only checked sign-in.
fixed text color of sign in button in access requirement list, also fixed check mark showing that someone was signed in when they were not.
=> Fix PORTALS-1425/1178

src/lib/utils/synapseTypes/OIDCAuthorizationRequest.ts
This doesn't affect the necessary change in the OAuth sign-in app: https://github.com/Sage-Bionetworks/synapse-oauth-signin/pull/27
Just creating a PR here to keep the object definition up-to-date
=> PLFM-6322 - OIDCAuthorizationRequest.claims is now an object

src/__tests__/lib/containers/CardContainer.test.tsx, src/__tests__/lib/containers/GenericCard.test.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/HeaderCard.tsx, src/lib/containers/row_renderers/utils/Icon.tsx, src/lib/containers/widgets/FileHandleLink.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/SynapseConstants.ts, src/lib/utils/hooks/useGetInfoFromIds.ts, src/lib/utils/synapseTypes/FileHandleAssociation.ts
CardContainer 
- Convert to a react hook so that the useGetInfoFromIds hook could retrieve the entity concrete type from the data being passed in
Generic Card
- Take in new props `tableId`, `tableEntityConcreteType` to support linking the filehandleId, initially only supporting the link from the title, but this will eventually need to get added to the secondary label rendering as well as the synapsetable cell renderer
- Added a test to validate that the FileHandleLink component receives the right props
- renamed variable returned from renderTitleLink: linkDisplay -> href
(clicking on the title **5XFAD** will take you to the file handle download)
SynapseClient
- Added new API call for getting file handle URL
=> PORTALS-1499

src/__tests__/lib/containers/TotalQueryResults.test.tsx, src/lib/containers/Error.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/SignInButton.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/style/base/_core.scss, src/lib/style/components/_all.scss, src/lib/style/components/_cards.scss, src/lib/style/components/_error.scss, src/lib/utils/SynapseClient.ts
Example of error message showing up -
SynapseClient -
simplified logic
removed retry count and only use exponential backoff
expand number of cases when backoff is used, including 500 error codes
added new SynapseClientError type
HasAccess -
Catch 404 error and prevent infinite loop 😅 
SynapseTable - 
Fix check for rendering hasaccess column to see that underlying entity is of type EntityView
=> simplify api retry logic, add error message to querywrapper

src/__tests__/lib/containers/SynapseTable.test.tsx, src/demo/containers/playground/Playground.tsx, src/demo/containers/playground/QueryWrapperMenuDemo.tsx, src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/demo/containers/playground/ThemesPlotDemo.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/query_wrapper_plot_nav/TopLevelControls.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/table/table-top/EllipsisDropdown.tsx, src/lib/containers/widgets/themes-plot/ThemesPlot.tsx, src/lib/containers/widgets/themes-plot/types.ts, src/lib/style/base/_core.scss, src/lib/style/components/_cards.scss
Fixed dropdown menu on SynapseTable, was broken functionally. I have an image of the menu for reference -
- Hoisted state from ColumnSelection state into SynapseTable while still letting it use its own state for when it gets used with the TopLevelControls component
- Added back state variable to track if the export metadata modal is open
Also fixed color of download icon, on the portals its colors are swapped. 
Changed HasAccess to only log backend issues, not the client side error that is thrown. This was cluttering the console output heavily.
Added tests to SynapseTable to validate that the ellipsis dropdown works, the HasAccess column doesn't show when isFileView is false
PORTALS-1482 - Expose event from the ThemesPlot so that ctrl-click can be detected and open link in new tab
=> PORTALS-1508

src/lib/style/components/_query-wrapper-plot-nav.scss
before: icons on the right side overflow the container, they stretch beyond the width of the gray line
after: icons don't overflow
=> fix overflow of icons on firefox

src/lib/containers/access_requirement_list/AcceptedRequirements.tsx, src/lib/containers/access_requirement_list/AccessRequirementList.tsx, src/lib/containers/access_requirement_list/SelfSignAccessRequirement.tsx, src/lib/containers/access_requirement_list/TermsOfUseAccessRequirement.tsx, src/lib/containers/download_list/DownloadListTable.tsx, src/lib/style/base/_core.scss
Tweaks to modal:
- limit modal height
- bootstrap modal.body was empty, moved content inside of it..
- removed unnecessary wrapping div
also fixed way too many divs in access requirement list component 😨 
before:
after:
=> limit modal height, fix too many divs

src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/table/SynapseTable.tsx
the component was not resetting the isFetchingEntityHeaders variable to false when it would update without actually making an API call. Restructured the method so this circumstance doesn't happen anymore
=> PORTALS-1517

package.json, src/lib/containers/UpsetPlot.tsx
and hide Upset.js plot export buttons for now (styling is lost on redirect to share embed site)
=> bump version to prep for release of 1.15.2

src/__tests__/lib/utils/functions/sqlFunctions.test.ts, src/lib/containers/GenericCard.tsx, src/lib/types.d.ts, src/lib/utils/functions/sqlFunctions.ts
To support [PORTALS-1575](https://sagebionetworks.jira.com/browse/PORTALS-1575) the sql parser needs to work with versioned entities which it currently does not. Modified the parser to recognize a versioned entity and fix the tokens accordingly.
Miscellaneous:
- Added a return type to `formatSQLFromParser`
- Added types for the sql-parser library inside of SRC
- fixed bug in renderValueOrMultiValue by checking null params
- changed synapse regex to recognize a versioned table
- Changed switch statement to use `default` to be more generic
=> PORTALS-1575

package.json, src/lib/utils/SynapseClient.ts, src/lib/utils/synapseTypes/OIDCAuthorizationRequest.ts
Also fix type definition for OIDCAuthorizationRequest (not hard-coding responseType)
=> SWC-5286 : do not throw away other error response json data (used to only hold onto "reason").

src/lib/containers/UserCardMedium.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_cards-rotate.scss, src/lib/style/components/_cards.scss, src/lib/style/components/_goals.scss
- Fix box shadow styling to match Goal cards. 
- Move inline CSS to stylesheet.
=> PORTALS-1627: Apply softer box shadow

package.json, src/demo/containers/playground/QueryWrapperPlotNavDemo.tsx, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/GenericCard.tsx
This is to help with the AMP-AD study name match. Ideally these would be synapse IDs
=> PORTALS-1678: option to wrap the matching value with parens

src/lib/containers/UserCardList.tsx, src/lib/style/base/_core.scss
I think this must have been a misunderstanding.  If items are in a bootstrap responsive grid, then the row already has a -15px margin (left and right) to correct for the columns which have a 15px padding (left and right).
=> remove SRC-adjust-for-bootstrap-margin

src/lib/style/base/_core.scss, src/lib/style/components/_download-link.scss
Bootstrap modal dialogs are already centered, and have better responsive behavior than results from the current css overrides.  Delete.
=> PORTALS-1699

src/lib/style/components/_carousel.scss
In Safari, zoom causes the flex container height to change, and the zoom-ed element 'pops' and seems to re-render children after the animation ends. Fixes with transform, which is fine across all browsers
=> SWC-5318: zoom has weird behavior on safari; use transform

src/lib/style/components/_project-view-card.scss
Before, a taller-than-expected image would push contents off of the card:
After:
=> PORTALS-1786: Limit the image height in ProjectViewCard

src/lib/style/components/synapse_form_wrapper/_steps-side-nav.scss, src/lib/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
Sass changed its interpolation behavior between LibSass/node-sass and Dart Sass. We previously caught a few cases where this broke Sass compilation. Here are a few places where sass successfully compiled, but produced invalid CSS
=> Missed some changes from node-sass to Dart Sass

src/__tests__/lib/containers/personal_access_token/CreateAccessTokenModal.test.tsx, src/lib/containers/personal_access_token/CreateAccessTokenModal.tsx
https://sagebionetworks.jira.com/browse/SWC-5356
* Embedding the modal content inside a `Form` tag and adding the `submit` type to the submit button triggers a submission when pressing 'enter'
* In some situations, the page would reload on the keypress, which is avoided by calling `preventDefault`
* Tab does not currently cycle through checkboxes, but this is an issue with all checkboxes and radio buttons on Synapse. Tracking this issue in [SWC-5372](https://sagebionetworks.jira.com/browse/SWC-5372)
=> SWC-5356: CreateAccessTokenModal -- 'enter' keypress should trigger submit

src/lib/style/components/_download-list.scss
=> SWC-5374 Remove unscoped button style

src/__tests__/lib/containers/MarkdownSynapse.test.tsx, src/lib/containers/MarkdownSynapse.tsx, src/lib/containers/synapse_form_wrapper/SynapseFormSubmissionsGrid.tsx, src/lib/style/components/_markdown.scss, src/lib/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
Use a span instead of a div for non-centered buttons
v1.15.56 (before regression):
Current:
After: 
Also, convert a form button to BS4 so it gets the theme color reliably.
=> Fix inline MD buttons + convert another button to BS4

src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/style/components/facet_nav/_facet-nav.scss
This fix is for Jira issue: https://sagebionetworks.jira.com/browse/PORTALS-1808.
Allows the size of the graph containers to shrink as the screen width gets smaller. This solves the problem of having three graphs that are stacked together, with two on top and one on the bottom. Some images of the fix can be seen below:
When the window size is normal:
When the window size decreases:
When the "Show All Graphs" button is pressed:
=> PORTALS-1808: Reformat Graphs Based On Screen Size

package.json, yarn.lock
Removes a dependency on `node`
=> Bump markdown-it-synapse

src/lib/containers/row_renderers/utils/CardFooter.tsx
This happen when the Synapse table status icon value changes and the portal config is not updated with the new value. For example "Partially Available" is changed to "Partially Released". We should always return the status value.
=> PORTALS-1783: Bug fix for missing icon config

package.json, src/lib/containers/VisibilityObserver.tsx, yarn.lock
Planning to use the `useInView` hook in the Entity Finder.
See docs: https://github.com/thebuilder/react-intersection-observer#hooks-
=> Upgrade react-intersection-observer to latest version

package.json, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/HeaderCard.tsx
Expand descriptionLinkConfig to define if the description should be expanded by default (shown in full), in addition to whether it should be processed as Markdown.
Also add "thumbnailRequiresPadding", which will pad the icon or image by 21px (matches padding-top of card type UI element).
=> PORTALS-1854

package.json, src/lib/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
only apply to elements under SRC-ReactJsonForm
=> SWC-5440: change scope of btn success override for forms

src/lib/containers/StyleGuidistComponentWrapper.tsx, src/lib/containers/synapse_form_wrapper/SynapseFormWrapper.md, styleguide.config.js
introduce a memoryrouter for components that rely on the router environment (like Prompt, Switch, Link, and others)
=> new StyleGuidist component wrapper

package.json, src/lib/style/components/_cards-rotate.scss
It's this problem:
https://twitter.com/wesbos/status/1256229763225657348/photo/1
Need to set the overflow of the grid items to hidden for it to respect the grid layout (note the text overflow of the paragraphs is already set properly, so it renders ellipsis when long values are truncated).
=> fix home page user grid

rollup.config.js, src/__tests__/lib/containers/widgets/facet-nav/FacetNav.test.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx
* Omit json-schema-ref-parser because it breaks the UMD build without error when accidentally bundled. See [JIRA](https://sagebionetworks.jira.com/browse/PORTALS-1907).
* Remove uses of `lodash`. We use `lodash-es`, which works better with Rollup's tree shaking and reduces the build size, if it happens to be included.
=> PORTALS-1907

src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/SelectionPane.tsx, src/lib/containers/entity_finder/tree/TreeView.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/base/_core.scss, src/lib/style/components/entity_finder/_details-view.scss, src/lib/style/components/entity_finder/_entity-finder.scss, src/lib/style/components/entity_finder/_tree-view.scss
* [SWC-5563](https://sagebionetworks.jira.com/browse/SWC-5563) Added a colon to the "Browse" text
* [SWC-5565](https://sagebionetworks.jira.com/browse/SWC-5565) Reduced border width
* [SWC-5566](https://sagebionetworks.jira.com/browse/SWC-5566) Fixed column headers in table view in Chrome not being totally top-aligned
* [SWC-5568](https://sagebionetworks.jira.com/browse/SWC-5568) Reworked how width is set and propagated to get a nice CSS transition when toggling search. This will have the desired effect of animating the modal size in SWC (which uses `width: max-content`, so it cannot be animated itself).
https://user-images.githubusercontent.com/17580037/115899913-5d41a980-a42d-11eb-8d82-d721857f0789.mov
* [SWC-5571](https://sagebionetworks.jira.com/browse/SWC-5571) Set a max height on …
=> Entity Finder scrub: SWC-5563, SWC-5565, SWC-5566, SWC-5568, SWC-5571

src/__tests__/lib/containers/widgets/Checkbox.test.tsx, src/__tests__/lib/containers/widgets/RadioGroup.test.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/template_style/_form.scss
Before, you could not navigate to checkboxes with tab (because the `input` had `display: none`) and you could not tell when you had navigated to a radio button.
After (note, added a radio group to this modal just for this clip):
https://user-images.githubusercontent.com/17580037/116572577-17c42700-a8da-11eb-9a76-2d1c411cb1d8.mov
=> SWC-5372: Add focus style to custom checkboxes and radio options

src/__tests__/lib/containers/widgets/facet-nav/FacetNav.test.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx, src/lib/style/abstracts/_variables.scss, src/lib/style/components/_query-wrapper-plot-nav.scss, src/lib/style/components/_total-query-results.scss, src/lib/style/components/facet_nav/_facet-nav.scss
Depends on #1002 
After clicking View All:
Once the viewport narrows enough, flex-grow causes the graphs expand to fill the width
Kind of weird side effect of flex grow, if there's an odd number of graphs:
=> PORTALS-1821

package.json, src/lib/index.ts
In this [PR](https://github.com/Sage-Bionetworks/Synapse-React-Client/pull/1023/files), I forgot to export the ExperimentalMode component in SRC. This PR is to add it back.
=> PORTALS-1924: Add Experimental Mode in Portals Footer

package.json, src/lib/containers/ExperimentalMode.tsx
This is to fix the issue of not being able to delete the cookie if a path is specified.
=> PORTALS-1924: Experimental mode bug fix

src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/style/components/entity_finder/_entity-finder.scss
#1019 slightly changed how bootstrap inputs look
This broke the visual styling of the customized entity finder input. This is easily fixed by not using bootstrap here
=> Fix EntityFinder input customization

src/__tests__/lib/containers/widgets/facet-nav/FacetNav.test.tsx
On my machine, reduces speed of this test suite from ~40s to ~13s!
Apparently, `getByRole` is really slow, and gets even worse when you combine it with `waitFor`. It's frustrating that `getByRole` is the most highly recommended way to identify a particular component, and `waitFor` is necessary/recommended to catch rendering changes (and remove the "...not wrapped in `act`..." warnings).
For more details, see issue: https://github.com/testing-library/dom-testing-library/issues/820
Maintainers of other packages have found some workarounds, such as allowing `getByRole` to return hidden nodes in dev, but not in CI
=> FacetNav: Speed up tests

package.json, src/lib/containers/HeaderCard.tsx
introduced in PORTALS-1853 about 3 months ago, but is not shown in NF because anchor color override
=> remove SRC-blacktext from header card heading

.eslintrc.json, src/__tests__/lib/containers/UserCardTests.test.tsx, src/__tests__/lib/utils/SynapseClient.test.tsx, src/lib/containers/Login.tsx, src/lib/containers/LoginPage.tsx, src/lib/containers/UserCard.tsx, src/lib/containers/UserCardContextMenu.tsx, src/lib/containers/UserCardMedium.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/tree/TreeNode.tsx, src/lib/containers/entity_finder/tree/TreeView.tsx, src/lib/testutils/TestingLibraryUtils.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/functions/EntityTypeUtils.ts, src/lib/utils/functions/getEndpoint.ts, src/lib/utils/functions/getUserData.ts, src/lib/utils/hooks/SynapseAPI/useUserBundle.ts, src/lib/utils/synapseTypes/CloudProviderFileHandle.ts, src/lib/utils/synapseTypes/DoiAssociation.ts, src/lib/utils/synapseTypes/EntityHeader.ts, src/lib/utils/synapseTypes/FileHandle.ts, src/mocks/MockSynapseContext.tsx, src/mocks/entity/mockEntity.ts, src/mocks/mockSchema.ts, src/mocks/mock_file_handle.ts, src/mocks/msw/handlers.ts, src/mocks/msw/server.ts, src/mocks/user/mock_user_profile.ts
None of this is directly related to SWC-5620 but all of these changes made developing/testing SWC-5620 easier. Most of the changes are related to mocks and running msw.
Summary:
* Refactored UserCard (it was hard to test UserCard with msw in new components for SWC-5620)
* Now uses existing hook to fetch user data and profile picture. Previously, UserCard was using a sessionStorage cache, but now it uses react-query and duplicated logic to fetch a profile picture was removed.
* Refactored UserCardMedium
* Converted from class component to function component
* This was unnecessary, but it made it easier for me to reason with the component's lifecycle. I can revert if desired.
* UserCardTests.test.tsx changes
* Now uses Mock Service worker. The worker only gets invoked for one or two tests, …
=> SWC-5620 pre-work

src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx
define the dependencies necessary to update after oauth page reload
=> PORTALS-1959: refactor old code to use new entity bundle hook

package.json, src/lib/containers/row_renderers/utils/CardFooter.tsx, src/lib/style/base/_core.scss
In portals, table data element is much larger than the button.  But we can't just set the css class on the button since the border definition in SRC-basicButton overrides.  So make this a button-specific css style.
=> fix selector specificity issue discovered in portals

src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx
The issue in PORTALS-1982 cannot be reproduced but removed the redundant condition to improve clarity.
=> PORTALS-1982: Remove redundant condition

src/__tests__/lib/containers/personal_access_token/CreateAccessTokenModal.test.tsx
Timing issue with async calls in unit tests breaks Travis build, so skipping the failed test to see if the build will pass. See https://sagebionetworks.jira.com/browse/PORTALS-1984
=> PORTALS-1981: Skip failed test

package.json, src/lib/style/components/_synapse-nav-drawer.scss
Discovered material UI drawer already has a default z-index that is above the background click capture layer for modals!
=> quick followup release for SWC-5700

package.json, src/__tests__/lib/containers/entity/metadata/AnnotationsTable.test.tsx, src/__tests__/lib/containers/entity/metadata/EntityModal.test.tsx, src/lib/containers/entity/annotations/CustomArrayFieldTemplate.tsx, src/lib/containers/entity/annotations/SchemaDrivenAnnotationEditor.tsx, src/lib/containers/entity/metadata/AnnotationsTable.tsx, src/lib/containers/entity/metadata/EntityModal.tsx, src/lib/rollup.index.ts, src/lib/style/components/_annotations.scss, src/lib/utils/hooks/SynapseAPI/useEntity.ts, src/lib/utils/synapseTypes/Entity.ts, src/mocks/msw/handlers.ts, yarn.lock
* Adds the annotation editor to the EntityModal. In Synapse.org, the 'Annotations' button will open the EntityModal, directly opening the annotations tab (the tab buttons will not be rendered, so functionally it will just be an annotations modal). If the user has edit access, they will see an edit button that opens the editor in the same modal.
* The annotations table now uses the JSON representation of the annotations rather than the bundle's annotations
* The data is now instantly updated in the cache when successfully updated, so no need to re-fetch the bundle
* Reduces chances of exposing inconsistencies between JSON and Annotations APIs (e.g., you can set annotations like 'name' in the old API).
* There were performance concerns about using the JSON API for reads, but it will soon be …
=> Add new Annotation Editor to Entity Modal + other changes

src/demo/containers/playground/ToastDemo.md, src/demo/containers/playground/ToastDemo.tsx, styleguide.config.js
Styleguidist uses react-docgen to parse components. Specifying a markdown file as a component causes an issue where react-docgen expects to see JS/TS, but instead sees markdown, so it reports errors.
The fix is to create an actual component and just call it from the markdown example.
=> Fix ghpages deploy

package.json, src/__tests__/lib/containers/entity/annotations/AnnotationEditorUtils.test.ts, src/__tests__/lib/containers/entity/annotations/SchemaDrivenAnnotationsEditor.test.tsx, src/lib/containers/entity/annotations/AdditionalPropertiesSchemaField.tsx, src/lib/containers/entity/annotations/AnnotationEditorUtils.ts, src/lib/containers/entity/annotations/CustomArrayFieldTemplate.tsx, src/lib/containers/entity/annotations/CustomDefaultTemplate.tsx, src/lib/containers/entity/annotations/CustomTextWidget.tsx, src/lib/containers/entity/annotations/FieldDescriptionTable.tsx, src/lib/containers/entity/annotations/SchemaDrivenAnnotationEditor.tsx, src/lib/style/components/_annotations.scss, src/mocks/mockSchema.ts, yarn.lock
[SWC-5724](https://sagebionetworks.jira.com/browse/SWC-5724)
When a schema author defines an enumeration using `anyOf`, the client-side validator doesn't recognize that it's an enumeration, so the error message when making an invalid selection is verbose and hard to understand. This change tries to recognize when we see errors that represent this situation, and transforms the errors to simplify what we show the user.
Before:
After:
[SWC-5684](https://sagebionetworks.jira.com/browse/SWC-5684) incorporates a collapsible description element from the Figma design:
https://user-images.githubusercontent.com/17580037/131906800-5c8bd4c8-6100-448b-97a7-849144c42198.mov
[SWC-5762](https://sagebionetworks.jira.com/browse/SWC-5762) initializes arrays as empty, rather than null, which allows users to …
=> SWC-5724, SWC-5684, SWC-5762

package.json, src/__tests__/lib/containers/widgets/Checkbox.test.tsx, src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/lib/containers/entity_finder/details/view/DetailsViewRow.tsx, src/lib/containers/personal_access_token/CreateAccessTokenModal.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/Checkbox.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, yarn.lock
[Jira](https://sagebionetworks.jira.com/browse/PORTALS-2013)
Bug in portals was caused by rendering two QueryWrapperPlotNavs with some identical EnumFacetFilter options. The checkboxes in the facet filter component had identical IDs, which would cause the browser to act as if you checked the first box in the page with that ID.
The simple fix is to generate unique IDs for all of our custom inputs.
=> PORTALS-2013 - fix for input collision

src/lib/containers/download_list_v2/DownloadListActionsRequired.tsx, src/lib/containers/download_list_v2/DownloadListTable.tsx, src/lib/containers/entity_finder/details/configurations/EntityChildrenDetails.tsx, src/lib/containers/entity_finder/details/configurations/ProjectListDetails.tsx, src/lib/containers/entity_finder/details/configurations/SearchDetails.tsx, src/lib/containers/entity_finder/tree/TreeNode.tsx, src/lib/containers/entity_finder/tree/TreeView.tsx, src/lib/containers/user_profile_links/UserChallenges.tsx, src/lib/containers/user_profile_links/UserProjects.tsx, src/lib/containers/user_profile_links/UserTeams.tsx, tsconfig.build.json, tsconfig.json
Assuming our rollup/babel configuration is working, we're transpiling and polyfilling down to es5, so this shouldn't cause any issues.
We can take advantage of ES2019's Array.prototype.flatMap to get rid of this ugly transform we've had to do whenever we call useInfiniteQuery
=> Target es2019 to get rid of horrific concat.apply

src/__tests__/lib/containers/GenericCard.test.tsx, src/__tests__/lib/containers/SynapseTable.test.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/HeaderCard.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/row_renderers/Dataset.tsx, src/lib/containers/row_renderers/Funder.tsx, src/lib/containers/synapse_table_functions/SynapseTableCell.tsx, src/lib/containers/table/SynapseTable.tsx
- Adds `ColumnSpecifiedLink` type, which allows you to format a SynapseTableCell with a link defined by another column. 
- Works for both cards and tables
- Convert function `renderLabel` to component `SynapseCardLabel`
- Convert function `renderTableCell` to component `SynapseTableCell`
- Typing cleanup in various card components
Screenshot working in the AD Portal. The first two rows have an empty `link` field
=> PORTALS-2002

src/__tests__/lib/containers/widgets/EnumFacetFilter.test.tsx, src/__tests__/lib/containers/widgets/RangeFacetFilter.test.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/query-filter/RangeFacetFilter.tsx, styleguide.setup.js
Toast just gets out of your way a little easier than `alert`, if you don't interact with it, it dismisses in 5s.
Using MUI's Collapse in the facet filters just adds a nice animation. No ticket for this, was just bothering me while I was looking into another potential issue and it's a simple change.
Toast:
https://user-images.githubusercontent.com/17580037/134222206-d4b772e8-2176-4e36-8f45-c288d6639687.mov
FacetFilter before:
https://user-images.githubusercontent.com/17580037/134222796-58dc7274-b1cc-4a93-a88b-11c2797c45b1.mov
FacetFilter after:
https://user-images.githubusercontent.com/17580037/134222827-1fe92c42-bf04-4aa1-b9dd-bf838344d1bd.mov
=> Use Toast in Styleguide, Use Collapse in FacetFilters

package.json, src/lib/containers/PlotlyWrapper.md, src/lib/containers/PlotlyWrapper.tsx, src/lib/rollup.index.ts, yarn.lock
Note that this breaks boxplot example, but this has been removed from the MVP for the near-term release
=> PORTALS-2022: attempt to fix build by not including full plotly.js in export bundle

src/__tests__/lib/containers/entity_finder/EntityFinder.test.tsx, src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx
Fixes [SWC-5840](https://sagebionetworks.jira.com/browse/SWC-5840) and [SWC-5845](https://sagebionetworks.jira.com/browse/SWC-5845)
SWC-5840 is a bug where the entity finder doesn't utilize the full width if the viewport is wide enough. This is fixed by always autosizing with a min width, rather than disabling autosize in certain situations.
SWC-5845 is a bug where hidden items take up space in the Entity Finder's DetailsView table. The simple fix is to exclude hidden items from the table data. Before, were hiding them with CSS, and the row virtualization technique would still create a space for the hidden row.
I discovered SWC-5845 while testing search, so also added an optimization where we will only search for entity types that can be selected. This should make searching more efficient …
=> SWC-5845 and SWC-5840

src/demo/containers/playground/ButtonDemo.tsx, src/demo/style/DemoStyle.scss, src/lib/style/abstracts/_mixins.scss, src/lib/style/abstracts/_variables.scss, src/lib/style/base/_icons.scss, src/lib/style/bootstrap4_backports/_base-import.scss, src/lib/style/components/_carousel.scss, src/lib/style/components/_project-view-card.scss, src/lib/style/components/_query-filter.scss, src/lib/style/components/entity_finder/_entity-finder.scss, src/lib/style/components/entity_finder/_selection-pane.scss
Utilizing this in the new component. I think we will likely apply these changes to Synapse before the component comes out of experimental mode.
The only visual change is that the primary palette's '500' item is no longer a super-saturated version of the primary action color. This change will be visible in a few Synapse.org components and portals, but shouldn't break anything.
=> SWC-5784 - New design system color palettes and buttons

src/lib/containers/FullTextSearch.tsx
Disallow adding duplicate TextMatchesQueryFilter to the additionalFilters array.  Also, let's reset the search string text after adding the filter.
=> PORTALS-2093

src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/__tests__/lib/containers/entity/annotations/SchemaDrivenAnnotationsEditor.test.tsx, src/lib/assets/skeletons/SkeletonInlineBlock.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx, src/lib/containers/download_list/DownloadDetails.tsx, src/lib/style/components/_download-confirmation.scss, src/lib/utils/synapseTypes/DownloadListV2/QueryResponseDetails.ts
[Jira](https://sagebionetworks.jira.com/browse/SWC-5922)
- Add a text warning before adding items to the download list when there are already items in the list.
- Add skeletons to (old) DownloadDetails
When items in DL list > 0:
Video showing skeletons:
https://user-images.githubusercontent.com/17580037/151575954-87918d99-d0a4-47ee-b1c7-8ea49145bb99.mov
=> SWC-5922: Warn before adding items to the download list when DL list is not empty

src/__tests__/lib/containers/Login.test.tsx, src/lib/containers/Login.tsx
We'll want to make sure this update hits SWC, Portals, and the OAuth app
=> SWC-5805 - use `current-password` for login

package.json, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.md, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/TopLevelControls.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/utils/functions/EntityTypeUtils.ts
For many cases, the new dataset entity type works identically to file views. In many places, we must update our checks to see if a table is a file view or dataset.
* TopLevelControls - Show add to download list for Datasets
* SynapseTable - Show direct download/add to download cart columns for Datasets
=> PORTALS-2113

src/__tests__/lib/containers/personal_access_token/AccessTokenPage.test.tsx
We have had inconsistent test runs in our CI and npm publish builds. [The last release took 3 runs to get a clean build](https://github.com/Sage-Bionetworks/Synapse-React-Client/actions/runs/2163664689), with 0 code changes. Unfortunately, the logs do not make it clear why the build has failed.
So I diff'd the fail logs with the success log and the major difference was this warning, which was present in the failed runs but absent from the successful run:
```
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "Warning: An update to AccessTokenPage inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* …
```
=> Improve test suite stability

src/__tests__/lib/containers/HasAccess.test.tsx, src/__tests__/lib/utils/hooks/useTheme.test.tsx, src/lib/containers/HasAccess.tsx, src/lib/containers/IconSvg.tsx, src/lib/utils/SynapseContext.tsx, src/lib/utils/hooks/useTheme.tsx, src/lib/utils/types/DeepPartial.ts
Tried to re-align the icons with circles and couldn't get it consistent in both SWC and portals. So let's just use the new icons.
=> Replace access icons with new MUI icons

src/lib/containers/FluidModal.tsx, src/lib/containers/entity/annotations/CustomAdditionalPropertiesFieldTemplate.tsx, src/lib/containers/entity/annotations/CustomObjectFieldTemplate.tsx, src/lib/containers/entity/annotations/SchemaDrivenAnnotationEditor.tsx, src/lib/containers/entity/metadata/EntityModal.md, src/lib/containers/entity/metadata/EntityModal.tsx, src/lib/style/components/_annotations.scss, src/lib/style/components/_entity-metadata.scss
Lots of weirdness in this Entity Modal/annotations editor UI that I decided to clean up. 
Most changes impact responsiveness of the modal in which we show the annotation editor. [SWC-5801](https://sagebionetworks.jira.com/browse/SWC-5801) was originally filed to address the new annotations editor. We created a `FluidModal` component that adheres to that spec for the Datasets -> Entity Finder use case. We're using it here now for the Entity metadata/annotations modal.
There are also a handful of changes that fix style issues.
Before:
https://user-images.githubusercontent.com/17580037/166263074-4df01996-b753-40b6-984f-1345487d77c6.mov
After:
https://user-images.githubusercontent.com/17580037/166262693-932cf86d-504b-47ed-b9d3-b9805014d20a.mov
=> SWC-5875 Follow up

src/__tests__/lib/containers/AccountLevelBadge.test.tsx, src/__tests__/lib/containers/CopyToClipboardInput.test.tsx, src/__tests__/lib/containers/DirectDownload.test.tsx, src/__tests__/lib/containers/EntityForm.test.tsx, src/__tests__/lib/containers/ErrorPage.test.tsx, src/__tests__/lib/containers/IconSvg.test.tsx, src/__tests__/lib/containers/Login.test.tsx, src/__tests__/lib/containers/TOC.test.tsx, src/__tests__/lib/containers/widgets/Checkbox.test.tsx, src/__tests__/lib/containers/widgets/RadioGroup.test.tsx, src/__tests__/lib/utils/hooks/useListState.test.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/MarkdownSynapse.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/template_style/_form.scss
Replacing Enzyme tests with RTL tests will
* Give us better confidence in testing behavior rather than implementation
* Unblock us from upgrading to >= React 17
This PR avoids touching actual components whenever possible. Any component changes typically facilitate good testing/accessibility practices, like adding appropriate ARIA roles to elements.
=> Rewrite Enzyme tests

src/lib/containers/dataaccess/SubmissionPage.tsx, src/lib/style/components/_submission-page.scss
Previously requesters were spaced out, making each row look like an independent unit of information, when they are actually related.
=> Tighten spacing between accessors

src/lib/utils/hooks/SynapseAPI/entity/useGetQueryResultBundle.ts
When we split QueryWrapper and InfiniteQueryWrapper, one optimization that we forgot to include in QueryWrapper is re-using the non-row data for a query (such as total count of results) when navigating between pages. Fetching data other than rows can be very expensive on the backend, so we should only request this data once. This should greatly improve performance when navigating between pages.
=> QueryWrapper: Split fetching stats and rows

src/__tests__/lib/containers/UserCardTests.test.tsx, src/lib/utils/SynapseClient.ts
Test suite fails with the following error:
```
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "Failed to parse response as JSON http://some-image-url.notarealurl/image.jpg".
313 |     responseObject = JSON.parse(responseBody) as TResponse | SynapseError
314 |   } catch (error) {
> 315 |     console.warn('Failed to parse response as JSON', responseBody)
|             ^
316 |   }
317 |
318 |   if (response.ok) {
at console.warn (node_modules/@jest/console/build/BufferedConsole.js:232:10)
at warn (src/lib/utils/SynapseClient.ts:315:13)
at step (node_modules/tslib/tslib.js:144:27)
at Object.next (node_modules/tslib/tslib.js:125:57)
at fulfilled (node_modules/tslib/tslib.js:115:62)
```
We could update this mock function to return …
=> Handle case where Synapse serves non-JSON

src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/details/view/DetailsViewTableRenderers.tsx, src/lib/containers/table/datasets/DatasetItemsEditor.tsx, src/lib/containers/widgets/Checkbox.tsx
Instead of providing an empty string as for a label, which is inaccessible, apply the label to the checkbox using `aria-label` and add the ability to hide the label with a new `hideLabel` prop.
=> Add aria-label for checkboxes without a visible label

src/__tests__/lib/utils/hooks/useGetIsAllSelectedInfiniteList.test.ts, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/configurations/EntityChildrenDetails.tsx, src/lib/containers/entity_finder/details/configurations/FavoritesDetails.tsx, src/lib/containers/entity_finder/details/configurations/ProjectListDetails.tsx, src/lib/containers/entity_finder/useEntitySelection.ts, src/lib/utils/hooks/useGetIsAllSelectedInfiniteList.ts
I was considering re-using `useGetIsAllSelectedFromInfiniteList` for the Trash Can page. I ultimately decided against it, but first rewrote the hook as it only worked with the Entity Finder.
In the hook and underlying function, replace Entity Finder-specific data structures with predicate arguments, so that the utility can be used with items of any type.
=> Generalize useGetIsAllSelectedInfiniteList

src/lib/style/bootstrap4_backports/_base-import.scss
Spacing is still OK when there are multiple buttons:
=> SWC-5637: Set modal-footer-margin-between to 0 because it breaks alignment

src/lib/style/bootstrap4_backports/_base-import.scss, src/lib/style/bootstrap4_backports/_overrides.scss, src/lib/style/components/entity_finder/_tree-view.scss
=> SWC-6017 - Dropdown icon from caret to chevron

src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/EntityFinderHeader.ts, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/configurations/ProjectListDetails.tsx, src/lib/containers/entity_finder/details/configurations/SearchDetails.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/tree/EntityTree.tsx, src/lib/containers/entity_finder/tree/VirtualizedTree.tsx, src/lib/utils/functions/EntityTypeUtils.ts, src/lib/utils/synapseTypes/Entity/Entity.ts, src/mocks/entity/mockFileEntity.ts
In order to handle the `modifiedOn` field in the tooltip, we need a consistent way to access the data fields within the EntityFinder. Let's convert all headers to a custom `EntityFinderHeader` type so we can handle all data in the same way.
=> SWC-5961b: Simplify types managed by EntityFinder

src/lib/utils/SynapseClient.ts
The initCredentials argument is used by only two methods in the entire client.
- Change the signature for all `fetch` wrappers to accept parameter `additionalOptions` with `fetch` options
- Include `credentials` in `additionalOptions` as needed
- Omit the new `additionalOptions` argument where undefined
Not related to any feature/bugfix, just decided to clean this up
=> Refactor SynapseClient to make initCredentials optional

src/lib/utils/SynapseClient.ts
By not returning the result of `doPost`, setAccessTokenCookie could resolve before the HTTP call completes.
=> Properly handle async code in setAccessTokenCookie

src/__tests__/lib/containers/UserCardTests.test.tsx, src/__tests__/lib/containers/UserSearchBoxV2.test.tsx, src/__tests__/lib/containers/dataaccess/AccessHistoryDashboard.test.tsx, src/__tests__/lib/containers/dataaccess/AccessRequirementDashboard.test.tsx, src/__tests__/lib/containers/dataaccess/AccessSubmissionDashboard.test.tsx, src/lib/containers/UserCardSmall.tsx, src/lib/style/base/_core.scss
- Refactor UserCardSmall to always render the same block of code
- When showFullName, render as Full Name (@username) instead of @username Full Name
- Remove color styling. It will have the correct color if it's a link.
SWC-5961 will utilize the new name ordering and should not have a color applied, as it will not be a link.
=> SWC-5961: UserCardSmall improvements

src/lib/containers/CardContainer.tsx, src/lib/containers/GenericCard.tsx, src/lib/containers/SubsectionRowRenderer.tsx, src/lib/containers/TableFeedCards.tsx, src/lib/containers/UpsetPlot.tsx, src/lib/containers/UserCardList.tsx, src/lib/containers/UserCardListRotate.tsx, src/lib/containers/home_page/featured_tools/FeaturedToolsList.tsx, src/lib/containers/home_page/goals/Goals.tsx, src/lib/containers/home_page/programs/Programs.tsx, src/lib/containers/home_page/project_view_carousel/ProjectViewCarousel.tsx, src/lib/containers/home_page/resources/Resources.tsx, src/lib/containers/synapse_table_functions/SynapseTableCell.tsx, src/lib/utils/synapseTypes/Table/QueryResult.ts
- The change causes typing issues in many portal components where we make the assumption that the rows will not contain a null value. Since these are typically controlled, curated tables, this is a safe assumption. In those cases, emit a warning to the console. We can refine how we handle those cases as needed.
- In other cases, use filtering or nullish coalescing to resolve type errors
=> Update type for QueryResultBundle: Row.values may include nulls

src/__tests__/lib/containers/QueryVisualizationWrapper.test.tsx, src/__tests__/lib/containers/widgets/ElementWithTooltip.test.tsx, src/lib/containers/QueryContext.tsx, src/lib/containers/QueryVisualizationWrapper.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/TopLevelControls.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/widgets/ElementWithTooltip.tsx, src/lib/style/base/_core.scss, src/mocks/msw/handlers/tableQueryHandlers.ts
- Remove unused toggleColumnSelection from SynapseTable
- Remove async from goToPage.
- Apply key to React.Fragment
- PORTALS-2272: Check selectColumn for deep equality before resetting visible columns
=> PORTALS-2272: Check selectColumn for deep equality before resetting visible columns

src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/lib/containers/IconSvg.tsx, src/lib/containers/entity_finder/EntityFinder.stories.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/entity_finder/VersionSelectionType.ts, src/lib/containers/entity_finder/details/EntityDetailsList.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/entity_finder/details/view/DetailsViewTableRenderers.tsx, src/lib/containers/entity_finder/details/view/VersionColumnHeader.tsx, src/lib/containers/table/datasets/DatasetItemsEditor.tsx, src/lib/utils/functions/EntityTypeUtils.ts
Replace `showVersionSelection`, `mustSelectVersionNumber`, and `latestVersionText` with an enum `versionSelection` that captures each possible case where we would want to change how a user can select versions.
The possible values for `versionSelection`, with examples, are
|Value|Description|Example Scenario|
|---|---|---|
|DISALLOWED|the user cannot select a version|Moving an entity, adding projects to a project view|
|REQUIRED|the user must select a version|Adding files to a dataset|
|TRACKED|the user may select a version, and contextually, changes to the latest version will be tracked if selected|Adding items to an entity list widget in a wiki
|UNTRACKED|the user may select a version, and contextually, changes to the latest version will NOT be tracked if selected. | Importing table …
=> SWC-6077: Contextually update latest version text

.storybook/preview-head.html, esbuild.config.mjs, index.html, package.json, src/lib/containers/MarkdownSynapse.tsx, src/setupTests.js, yarn.lock
v2 of sanitize-html removes the prebuilt version so it must be bundled.
Bundle size increases from ~2.32 MB to ~2.48 MB
=> SWC-6261: Bundle sanitize-html

.storybook/main.ts, package.json, vite.config.ts, yarn.lock
Upgrading and bundling sanitize-html caused some packages relying on missing polyfills to be included.
=> Update polyfills to fix broken storybook

src/__tests__/lib/containers/InfiniteQueryWrapper.test.tsx, src/__tests__/lib/containers/QueryWrapper.test.tsx, src/lib/containers/InfiniteQueryWrapper.tsx, src/lib/containers/QueryContext.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/RssFeedCards.stories.tsx, src/lib/containers/RssFeedCards.tsx, src/lib/containers/SearchV2.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/utils/functions/queryUtils.ts
Pre-work for PORTALS-2157
The "lock" we apply to hide charts/facets/active filters can be applied to any column; the locked column does not necessarily need to be faceted.
This is a breaking change, but it is easily caught by TypeScript.
=> PORTALS-2157: Rename LockedFacet to LockedColumn

src/__tests__/lib/utils/hooks/useImmutableTableQuery.test.tsx, src/lib/containers/InfiniteQueryWrapper.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/useImmutableTableQuery.ts, src/lib/utils/functions/queryUtils.ts
Most of the changes are refactoring I did to simplify PORTALS-2157 -- attempting to reduce duplicate code and improve test-ability. There is also one non-refactor change where we will now use the React Query cache in QueryWrapper and InfiniteQueryWrapper.
- Create custom hook `useImmutableTableQuery`, which has the following responsibilities
- Stores the initial and current table queries in state
- Provides clones of the table queries for consumers to read
- Provides functions for consumers to perform actions on the query
-	e.g. update the entire query object, change the page size or page number. We can provide more specific controls as needed, like adding/removing a facet filter, for example
- Handles side effects related to query updates (calling callbacks, updating URL)
- QueryWrapper …
=> Refactor: replace duplicate logic in Infinite/QueryWrapper with useImmutableTableQuery

.eslintrc.json
SWC-6277 was caused by an unstable component definition. Let's enable warnings for an ESLint rule that would have caught this.
=> SWC-6277: Add lint rule

src/__tests__/lib/containers/DownloadConfirmation.test.tsx, src/lib/containers/StyleGuidistComponentWrapper.tsx, src/lib/containers/download_list/DownloadConfirmation.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.stories.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/utils/SynapseContext.tsx, src/mocks/MockSynapseContext.tsx
When we add the Synapse Table renderer to the markdown component (PORTALS-2314), we need to specify the download cart page URL to ensure it links to the correct place. Instead of passing this information through the markdown renderer, it should be in global context.
=> BREAKING CHANGE: Specify downloadCartPageUrl in context

.husky/pre-commit, package.json, src/__tests__/lib/containers/UserSearchBoxV2.test.tsx, src/__tests__/lib/containers/dataaccess/AccessHistoryDashboard.test.tsx, src/__tests__/lib/containers/dataaccess/AccessRequirementDashboard.test.tsx, src/demo/containers/playground/Playground.tsx, src/lib/containers/ExternalFileHandleLink.tsx, src/lib/containers/UserSearchBoxV2.tsx, src/lib/containers/entity/annotations/AdditionalPropertiesSchemaField.tsx, src/lib/style/components/_user-search-box.scss, src/lib/utils/hooks/SynapseAPI/user/useUserGroupHeader.ts, src/lib/utils/synapseTypes/ExternalFileHandleInterface.ts, src/mocks/user/mock_user_profile.ts, yarn.lock
* Use builtin components for react-select (prevents unnecessary console warnings and fixes layout)
* Fix styling for react-select
* For UserSearchBoxV2, use react-query instead of `AsyncSelect`, which has unusual behavior (such as not properly resetting the options between selections)
* Add packages to package.json that we directly reference
* Remove references to modules that we don't need to use (e.g. `assert`)
=> SWC-6278: Fix UserSearchBox, dependency references

package.json, src/lib/containers/markdown/MarkdownSynapse.tsx, src/lib/utils/functions/SanitizeHtmlUtils.ts, yarn.lock
We're using xss to clean HTML in SWC, which is more configurable. Let's simplify our configs by using the same library. I also have more confidence in the SWC configuration, which we have been been using to clean arbitrary HTML for far longer.
This also brings the bundle size down from 3.06 MB to 2.91 MB
=> PORTALS-2316: Replace sanitize-html with xss

src/__tests__/lib/containers/markdown/FilePreview/HtmlPreview.test.tsx, src/lib/containers/FilePreview/HtmlPreview/HtmlPreview.tsx, src/lib/containers/FilePreview/HtmlPreview/SanitizedWarning.tsx, src/lib/umd.index.ts, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/SynapseConstants.ts, src/lib/utils/hooks/SynapseAPI/team/useTeamMembers.ts
Adds HtmlPreview component
- Given raw HTML and a file handle, renders the raw HTML (if the user is on the trusted team) or renders sanitized HTML.
- If the rendered HTML is different than the raw HTML, the user can open the untrusted content in a new window.
- Component has not yet been exposed via MarkdownSynapse - this PR does not include: 
- Parsing the `preview` widget descriptor
- Fetching the file referenced by the preview descriptor
- Asking the user to log in if they can't download the referenced file as Anonymous
- Determining how to preview the file (e.g. download the file contents or a preview file handle?)
- Downloading the file handle contents.
=> PORTALS-2316: HtmlPreview component

src/__tests__/lib/containers/markdown/FilePreview/FileHandleContentRenderer.test.tsx, src/__tests__/lib/containers/markdown/FilePreview/HtmlPreview/HtmlPreview.test.tsx, src/lib/containers/ErrorBanner.tsx, src/lib/containers/FilePreview/FileHandleContentRenderer.tsx, src/lib/containers/FilePreview/PreviewRendererType.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/hooks/SynapseAPI/file/useFiles.ts
Simply renders the contents of a file handle based on the predetermined type of preview shown.
The next PR will include a component that will determine which file handle to render for a particular entity.
=> PORTALS-2316: Add FileHandleContentRenderer

src/__tests__/lib/containers/markdown/FilePreview/EntityPreview.test.tsx, src/__tests__/lib/utils/functions/ResolveLinkEntity.test.ts, src/lib/containers/FilePreview/EntityPreview.tsx, src/lib/containers/FilePreview/FileHandleContentRenderer.tsx, src/lib/containers/entity_finder/EntityFinder.tsx, src/lib/containers/markdown/MarkdownSynapse.stories.tsx, src/lib/containers/markdown/MarkdownWidget.tsx, src/lib/containers/markdown/widget/MarkdownEntityPreview.tsx, src/lib/utils/functions/RegularExpressions.ts, src/lib/utils/functions/ResolveLinkEntity.ts
Depends on #1825 
* Add `EntityPreview`. `EntityPreview` takes a SynID and renders the appropriate preview based on the Entity type. For now, it only handles `FileEntity` and `Link`, if the `Link` resolves to a `FileEntity`.
* Add `MarkdownEntityPreview` which renders an `EntityPreview`, and register the component to handle the `preview` widget descriptor
=> PORTALS-2316: Add EntityPreview and register it with Markdown processor

src/__tests__/lib/containers/widgets/query-filter/FacetFilterControls.test.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/widgets/facet-nav/FacetNav.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/query-filter/FacetFilterControls.tsx, src/lib/style/components/_query-filter.scss, src/lib/style/components/_query-wrapper-plot-nav.scss
- Rename QueryFilter component to FacetFilterControls to avoid confusion with the [QueryFilter](https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/table/QueryFilter.html) object. The QueryFilter object is not used by the FacetFilterControls, since QueryFilters are not used with facets.
- Fix case where a facet chip would be shown when the corresponding facet control could not be shown
=> PORTALS-2157 - Rename QueryFilter component to FacetFilterControls and small bugfix

src/lib/style/components/_query-wrapper-plot-nav.scss
The TopLevelControls bar needs more padding to match the design. Looks weird right now because it doesn't have enough space.
Also moved the border from the top of the filter panel to the bottom of the top bar so it is always shown.
Before:
After (ignore incorrect label on facet pill):
=> PORTALS-2157: Small style fix

src/__tests__/lib/containers/CardContainerLogic.test.tsx, src/__tests__/lib/containers/dataaccess/AccessSubmissionDashboard.test.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/CardContainerLogic.tsx, src/lib/containers/InfiniteQueryWrapper.tsx, src/lib/containers/QueryContext.tsx, src/lib/containers/QueryVisualizationWrapper.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/query_wrapper_plot_nav/QueryWrapperPlotNav.tsx, src/lib/containers/table/NoContentPlaceholderType.ts, src/lib/containers/table/StandaloneQueryWrapper.tsx, src/lib/containers/table/SynapseTable.tsx, src/lib/containers/table/TableIsEmpty.tsx, src/lib/containers/widgets/query-filter/FacetFilterControls.tsx, src/lib/utils/functions/queryUtils.ts, src/lib/utils/synapseTypes/Table/FacetColumnRequest.ts
Depends on #1854 
- Add `noContentPlaceholderType` prop to QueryWrapperPlotNav, CardContainerLogic, and StandaloneQueryWrapper, which can be used to specify whether the UI should guide the user to change interactive filters
=> PORTALS-2157: Add NoContentPlaceholder to determine what to show when query results are empty

src/__tests__/lib/containers/widgets/ElementWithTooltip.test.tsx, src/lib/containers/InfiniteQueryWrapper.tsx, src/lib/containers/QueryContext.tsx, src/lib/containers/QueryVisualizationWrapper.tsx, src/lib/containers/QueryWrapper.tsx, src/lib/containers/TotalQueryResults.tsx, src/lib/containers/table/TopLevelControls.tsx, src/lib/containers/table/table-top/ColumnSelection.tsx, src/lib/containers/table/table-top/DownloadOptions.tsx, src/lib/containers/useImmutableTableQuery.ts, src/lib/containers/widgets/ElementWithTooltip.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.stories.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPill.tsx, src/lib/containers/widgets/facet-nav/SelectionCriteriaPills.tsx, src/lib/containers/widgets/query-filter/EnumFacetFilter.tsx, src/lib/containers/widgets/themes-plot/ThemesPlot.tsx, src/lib/utils/functions/getDataFromFromStorage.ts
- Refactor TotalQueryResults and SelectionCriteriaPill
- Query modification (e.g. dropping facet selection) is managed by useImmutableTableQuery
- Displaying a column name is managed by QueryVisualizationWrapper
- Remove prop `idForTooltip` from ElementWithTooltip (no longer needed)
=> PORTALS-2157: Refactor TotalQueryResults and SelectionCriteriaPill

src/lib/utils/SynapseContext.tsx, src/lib/utils/hooks/SynapseAPI/entity/useGetQueryResultBundle.ts
- react-query default stale time increased from 1m to 5m
- Table query stale time set to 30m
- default cacheTime increased from 5m to 30m.
=> SWC-6321: Increase react-query stale time defaults

src/__tests__/lib/containers/menu/ComplexMenu.test.tsx, src/lib/containers/menu/ComplexMenu.stories.tsx, src/lib/containers/menu/ComplexMenu.tsx, src/lib/utils/theme/DefaultTheme.ts
- Add ComplexMenu component used to combine multiple icon buttons and dropdown menus
- Update theme to disable ripple on all MUI button types, including IconButton
https://user-images.githubusercontent.com/17580037/204293516-7845791e-4798-4c17-b4d9-9da501ed765e.mov
=> SWC-6323: Add generic ComplexMenu component

src/__tests__/lib/containers/CardContainer.test.tsx, src/lib/containers/CardContainer.tsx, src/lib/containers/UserCardList.tsx, src/mocks/msw/handlers/userProfileHandlers.ts, src/mocks/query/mockUserCardTableQueryResultBundle.ts
- Fix case where a bad filter would cause us to mis-index a USERID column, and make a malformed request to the backend
- Add mock data and test to verify that users with/out fake data are not filtered
- Pass null fake userProfile ID instead of empty string, so we don't make further invalid calls to the backend
=> PORTALS-2430

package.json, src/__tests__/lib/containers/SynapseTable.test.tsx, yarn.lock
Change SynapseTable.test.tsx so it doesn't log errors
Add `jest-fail-on-console` and use it in SynapseTable to prevent future issues. We should try to add this to as many tests as possible (or setupFilesOnEnv)
=> PORTALS-2441: Fix flaky test

src/_tests_/lib/containers/entity/page/title_bar/TitleBarProperties.test.tsx, src/_tests_/lib/utils/functions/FileHandleUtils.test.ts, src/lib/containers/entity/metadata/MetadataTable.tsx, src/lib/containers/entity/page/title_bar/TitleBarProperties.tsx, src/lib/containers/entity/page/title_bar/useGetEntityTitleBarProperties.tsx, src/lib/containers/widgets/RadioGroup.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/functions/FileHandleUtils.ts, src/lib/utils/hooks/SynapseAPI/doi/useDOI.ts, src/lib/utils/hooks/SynapseAPI/file/useUploadDestination.ts, src/mocks/entity/mockFileEntity.ts, src/mocks/msw/handlers/entityHandlers.ts, src/mocks/msw/handlers/userProfileHandlers.ts
- Add TitleBarProperties component to handle rendering Entity property data
- Add useGetEntityTitleBarProperties hook to handle getting Entity property data
- Extract utilities from MetadataTable and move to FileHandleUtils to reuse
- Default mock handlers for upload destination, current user bundle
https://user-images.githubusercontent.com/17580037/210395280-3807affe-a0d5-4045-acd5-0d4d691f5a71.mov
=> SWC-6318: Add TitleBarProperties component

.storybook/preview.jsx, src/__tests__/lib/containers/dataaccess/SubmissionPage.test.tsx, src/lib/containers/StorybookComponentWrapper.tsx, src/lib/containers/dataaccess/RejectDataAccessRequestModal.stories.tsx, src/lib/containers/dataaccess/RejectDataAccessRequestModal.test.tsx, src/lib/containers/dataaccess/RejectDataAccessRequestModal.tsx, src/lib/containers/dataaccess/ReviewerDashboard.tsx, src/lib/containers/dataaccess/SubmissionPage.stories.tsx, src/lib/containers/dataaccess/SubmissionPage.tsx, src/lib/utils/SynapseClient.ts, src/lib/utils/SynapseConstants.ts, src/lib/utils/hooks/SynapseAPI/entity/queryKeys.ts, src/lib/utils/hooks/SynapseAPI/entity/useGetQueryResultBundle.ts, src/lib/utils/theme/DefaultTheme.ts, src/mocks/msw/handlers/tableQueryHandlers.ts, src/mocks/query/mockRejectionReasonsTableQueryResultBundle.ts
- Add RejectDataAccessRequestModal
- Create useGetFullTableQueryResults hook to wrap SynapseClient.getFullQueryTableResults
- Show RejectDataAccessRequestModal when rejecting a submission from the SubmissionPage component
- Add Storybook control to show/hide React Query Devtools
https://user-images.githubusercontent.com/17580037/212126432-a7d2e14d-4976-450f-a289-bf377c80e734.mov
=> SWC-6356: RejectDataAccessRequestModal

src/lib/containers/entity/page/title_bar/EntityPageTitleBar.tsx, src/lib/containers/entity/page/title_bar/TitleBarProperties.tsx, src/lib/containers/menu/DropdownMenu.tsx, src/lib/utils/theme/DefaultTheme.ts
- Adjust padding values in EntityPageTitleBar, TitleBarProperties per design
- Adjust height, sizing values in DropdownMenu per design
Ex. 1 - Top padding is now 20px
Ex. 2 - Padding above extra properties is now 20px
Ex. 3 - Height of dropdown menu items is now 38px (26px + 2*6px padding), less side padding (now 12px, was 16px)
Ex. 4 - Less space between icon and text (container has width of 30px, down from 36px). Also bumped icon size up 1px in height and width
=> SWC-6362 and SWC-6369: Entity Title Bar design tweaks

src/__tests__/lib/containers/entity_finder/tree/EntityTree.test.tsx, src/lib/containers/entity_finder/SelectionPane.tsx, src/lib/containers/entity_finder/tree/EntityTree.tsx, src/lib/utils/APIConstants.ts, src/lib/utils/SynapseClient.ts, src/lib/utils/hooks/SynapseAPI/entity/useGetEntityHeaders.ts, src/lib/utils/synapseTypes/EntityHeader.ts, src/lib/utils/types/Optional.ts
- Handle case where caller may not have access to the project in the EntityFinder
- Refactor EntityTree.tsx to use React Query to fetch favorites, entity path, entity header. Replace related useEffect with useMemo
- Refactor EntityTree tests to use MSW instead of mocking react-query and SynapseClient
- Denote the `name` field as potentially missing in the Entity Path object, which is a likely outcome of PLFM-7654
https://user-images.githubusercontent.com/17580037/213007696-e5b148b9-0ab8-41b5-b77d-15fee6dd626b.mov
=> SWC-6355: Handle case where caller does not have access to project in Entity Finder

src/__tests__/lib/containers/entity_finder/details/DetailsView.test.tsx, src/__tests__/lib/containers/table/datasets/DatasetItemsEditor.test.tsx, src/lib/containers/entity_finder/details/view/DetailsView.tsx, src/lib/containers/table/datasets/DatasetItemsEditor.tsx
- Dataset items editor will show data for the selected version of the dataset, such as annotations in the EntityBadgeIcons
- Entity Finder will show data for the selected version of the dataset, such as annotations in the EntityBadgeIcons
- Update DetailsView.test.tsx to reduce the amount of logged errors (mostly "not wrapped in act" warnings caused by not using RTL's `findBy*`)
Entity Finder:
https://user-images.githubusercontent.com/17580037/213246141-53436432-004f-4931-9d89-615001890edc.mov
Dataset Editor:
https://user-images.githubusercontent.com/17580037/213246325-ecccc25c-55ad-42aa-af47-2512566f0747.mov
=> SWC-6283: Show selected version data in Dataset Editor, Entity Finder

src/__tests__/lib/containers/widgets/facet-nav/FacetNav.test.tsx, src/__tests__/lib/containers/widgets/facet-nav/FacetNavPanel.test.tsx, src/lib/containers/widgets/facet-nav/FacetNavPanel.tsx
Tests in FacetNav are failing for me in TravisCI, not entirely sure why. I'm refactoring the tests (and one component change) to get rid of error logs that are either triggering or obscuring the failure reason.
- Use react-query instead of useEffect in FacetNavPanel, mostly to prevent error logs in test
- Attempt to make tests less flaky by refactoring to avoid error and warning logs
=> Attempt to fix flaky tests: FacetNav

src/__tests__/lib/containers/SynapseTable.test.tsx, src/lib/containers/synapse_table_functions/SynapseTableCell.tsx, src/lib/containers/table/SynapseTable.tsx
- SynapseTable: Don't create blank entity header if no header is fetched
- SynapseTableCell: pass ID to EntityLink component if no header was fetched.
=> SWC-6363: More gracefully handle error cases when rendering ENTITYID in tables
